import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
import {DIARY_ID,type Snapshot} from '../src/lib/contracts.ts';import {planResults,usageForDay} from '../src/lib/review.ts';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
async function fixture(){const db=new PGlite();await db.exec('create role anon;create role authenticated;create role service_role;');for(const file of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));let n=0,revision=0;
const send=async(command:string,payload:unknown)=>{const r=(await db.query<{data:{entityId:string;revision:number}}>('select public.haru_command($1,$2,$3,$4::jsonb) data',[id(++n),revision,command,JSON.stringify(payload)])).rows[0].data;revision=r.revision;return r;};
const snapshot=async()=>(await db.query<{data:Snapshot}>('select public.haru_snapshot() data')).rows[0].data;
const plan=await send('create_plan',{kind:'general',title:'원본 계획',startDate:'2026-09-01',endDate:'2026-09-30',estimatedMinutes:100});const task=await send('create_task',{planId:plan.entityId,title:'실제 할 일',dueDate:'2026-09-16',estimatedMinutes:60});
const run=await send('create_run',{taskId:task.entityId,startedAt:'2026-09-17T14:30:00Z',endedAt:'2026-09-17T15:30:00Z',blockedReason:'첫 이유',segments:[{kind:'work',startedAt:'2026-09-17T14:30:00Z',endedAt:'2026-09-17T14:50:00Z'},{kind:'pause',startedAt:'2026-09-17T14:50:00Z',endedAt:'2026-09-17T15:10:00Z'},{kind:'work',startedAt:'2026-09-17T15:10:00Z',endedAt:'2026-09-17T15:30:00Z'}]});return {db,send,snapshot,planId:plan.entityId,taskId:task.entityId,runId:run.entityId};}
test('thoughts require actual work on selected Seoul date and remain one per task/day',async()=>{const f=await fixture();try{await assert.rejects(f.send('save_thought',{taskId:f.taskId,date:'2026-09-19',body:'예정만으로 작성 안 됨'}),/Performed task/);const first=await f.send('save_thought',{taskId:f.taskId,date:'2026-09-18',body:'한 문장'});const second=await f.send('save_thought',{taskId:f.taskId,date:'2026-09-18',body:'고친 문장'});assert.equal(first.entityId,second.entityId);assert.equal((await f.snapshot()).thoughts.length,1);}finally{await f.db.close();}});
test('reflection imports are snapshots, can be edited after source changes, and are plan-independent',async()=>{const f=await fixture();try{const t=await f.send('save_thought',{taskId:f.taskId,date:'2026-09-18',body:'처음 단상'});const imports=[{id:t.entityId,body:'처음 단상'}];await f.send('save_reflection',{date:'2026-09-18',body:'나의 회고',imports});await f.send('save_thought',{taskId:f.taskId,date:'2026-09-18',body:'달라진 단상'});await f.send('save_reflection',{date:'2026-09-18',body:'고친 나의 회고',imports});await f.send('delete_entity',{entityType:'plan',entityId:f.planId});const s=await f.snapshot();assert.equal(s.reflections[0].body,'고친 나의 회고');assert.equal(s.reflections[0].imported_thoughts[0].body,'처음 단상');assert.equal((s.reflections[0].imported_thoughts[0] as unknown as {task_title:string}).task_title,'실제 할 일');assert.equal(s.plans.length,0);assert.equal(s.tasks.length,0);assert.equal(s.thoughts.length,0);}finally{await f.db.close();}});
test('day closure allows no reflection, but empty diary is never saved; bookmark remains only on reflections',async()=>{const f=await fixture();try{await f.send('close_day',{date:'2026-09-18',body:''});let s=await f.snapshot();assert.equal(s.closures.length,1);assert.equal(s.reflections.length,0);await assert.rejects(f.send('save_reflection',{date:'2026-09-18',body:''}));const r=await f.send('save_reflection',{date:'2026-09-18',body:'기억'});await f.send('bookmark_reflection',{reflectionId:r.entityId,bookmarked:true});s=await f.snapshot();assert.equal(s.reflections[0].bookmarked,true);assert.equal('plan_id' in s.reflections[0],false);}finally{await f.db.close();}});
test('trash restoration respects deletion batches and does not revive separately deleted children',async()=>{const f=await fixture();try{const other=await f.send('create_task',{planId:f.planId,title:'미리 삭제한 일'});await f.send('delete_entity',{entityType:'task',entityId:other.entityId});await f.send('delete_entity',{entityType:'plan',entityId:f.planId});let s=await f.snapshot();const parent=s.trash.find(t=>t.entity_type==='plan')!,child=s.trash.find(t=>t.entity_type==='task')!;await assert.rejects(f.send('restore_entity',{trashId:child.id}),/parent first/);await f.send('restore_entity',{trashId:parent.id});s=await f.snapshot();assert.equal(s.tasks.length,1);assert.equal(s.runs.length,1);assert.equal(s.trash.length,1);await f.send('restore_entity',{trashId:child.id});assert.equal((await f.snapshot()).tasks.length,2);}finally{await f.db.close();}});
test('next-plan improvement is copied atomically without replacing goals and deduplicates',async()=>{const f=await fixture();try{const p={kind:'general',title:'다음 계획',startDate:'2026-10-01',endDate:'2026-10-31',successText:'성공 기준 유지',sourcePlanId:f.planId,improvementText:'작게 나누기'};const next=await f.send('create_plan',p);await f.send('send_improvement',{sourcePlanId:f.planId,targetPlanId:next.entityId,body:'작게 나누기'});let s=await f.snapshot();assert.equal(s.improvements.length,1);assert.equal(s.plans.find(x=>x.id===next.entityId)!.success_text,'성공 기준 유지');const before=s;await assert.rejects(f.send('create_plan',{...p,title:'실패할 계획',improvementText:''}));assert.deepEqual(await f.snapshot(),before);await f.send('update_plan',{planId:f.planId,title:'바뀐 출처 제목',startDate:'2026-09-01',endDate:'2026-09-30'});s=await f.snapshot();assert.equal((s.improvements[0] as unknown as {source_plan_title:string}).source_plan_title,'원본 계획');}finally{await f.db.close();}});
test('review count/expected/actual/difference and evidence agree, pause merges into interrupt by date',async()=>{const f=await fixture();try{let s=await f.snapshot(),r=planResults(s,'all','all','2026-09-18');assert.deepEqual(r.values,{planned:1,complete:0,delayed:1,blocked:1,expected:3600000,actual:2400000,difference:-1200000});for(const key of ['planned','complete','delayed','blocked'] as const)assert.equal(r.evidence[key].length,r.values[key]);const first=usageForDay(s,'2026-09-17'),second=usageForDay(s,'2026-09-18');assert.equal(first.totals.work,1200000);assert.equal(first.totals.interrupt,600000);assert.equal(second.totals.work,1200000);assert.equal(second.totals.interrupt,600000);await f.send('set_task_complete',{taskId:f.taskId,complete:true});s=await f.snapshot();r=planResults(s,'all','all','2026-09-18');assert.equal(r.values.complete,1);assert.equal(r.values.delayed,0);assert.equal(r.values.blocked,1);await f.send('delete_entity',{entityType:'run',entityId:f.runId});r=planResults(await f.snapshot(),'all','all','2026-09-18');assert.equal(r.values.blocked,0);assert.equal(r.values.actual,0);}finally{await f.db.close();}});
test('export includes deleted records and audit evidence but excludes operational receipts and secrets; public diary export allowed',async()=>{const f=await fixture();try{await f.send('delete_entity',{entityType:'task',entityId:f.taskId});const exported=(await f.db.query<{data:{tasks:unknown[];runs:unknown[];revisions:unknown[]}}>('select public.haru_export() data')).rows[0].data;assert.equal(exported.tasks.length,1);assert.equal(exported.runs.length,1);assert.ok(exported.revisions.length);assert.equal('command_receipts' in exported,false);assert.equal('secret' in exported,false);await f.db.exec('set role anon');assert.ok((await f.db.query('select public.haru_export()')).rows.length);await assert.rejects(f.db.query('select journal.export_v4($1)',[DIARY_ID]),/permission denied/);}finally{await f.db.close();}});
test('restoring a deleted run overlapping another currently open run rolls back',async()=>{const f=await fixture();try{
 await f.send('delete_entity',{entityType:'run',entityId:f.runId});
 const other=await f.send('create_task',{planId:f.planId,title:'다른 진행 작업'});
 await f.send('start_run',{taskId:other.entityId,at:'2026-09-17T15:00:00.000Z'});
 const before=await f.snapshot();await assert.rejects(f.send('restore_entity',{trashId:before.trash[0].id}),/overlap/i);
 assert.deepEqual(await f.snapshot(),before);assert.equal(before.runs.length,1);assert.equal(before.runs[0].ended_at,null);
 }finally{await f.db.close()}});
