import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
import {addDays,dayItems,localInstant} from '../src/lib/schedule.ts';import {planResults} from '../src/lib/review.ts';import {routinePreview} from '../src/lib/routines.ts';import type {Snapshot} from '../src/lib/contracts.ts';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
async function fixture(){const db=new PGlite();await db.exec('create role anon;create role authenticated;create role service_role');for(const file of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));const today=(await db.query<{local_date:string}>("select to_char(now() at time zone 'Asia/Seoul','YYYY-MM-DD') as local_date")).rows[0].local_date;let n=0,revision=0;
 const call=async(command:string,payload:unknown,request=id(++n),expected=revision)=>{const r=(await db.query<{v:{entityId:string;revision:number}}>('select public.haru_command($1,$2,$3,$4::jsonb) v',[request,expected,command,JSON.stringify(payload)])).rows[0].v;revision=r.revision;return r};const snapshot=async()=>(await db.query<{v:Snapshot}>('select public.haru_snapshot() v')).rows[0].v;
 const fields={kind:'routine',title:'매일의 루틴',startDate:today,endDate:addDays(today,6),estimatedMinutes:100,priority:'normal'},p=await call('create_plan',fields);
 const draft={title:'독서',description:'매일 읽기',startDate:today,endDate:addDays(today,6),estimatedMinutes:20,priority:'normal',tags:['독서'],timing:'flex',time:'09:00',allowOverlap:false};return {db,today,call,snapshot,planId:p.entityId,draft,fields};}
test('routine period, date IDs and exact retry persist; counts are rules, review excludes occurrences',async()=>{const f=await fixture();try{await f.db.exec('set role anon');const before=await f.snapshot(),payload={...f.draft,planId:f.planId},r=await f.call('create_routine',payload,id(90),before.revision);assert.deepEqual(await f.call('create_routine',payload,id(90),before.revision),r);const s=await f.snapshot();assert.equal(s.routines?.length,1);assert.equal(s.tasks.length,7);assert.equal(new Set(s.tasks.map(t=>t.occurrence_date)).size,7);assert.equal(dayItems(s,f.today).tasks.length,1);assert.equal(planResults(s,'all','all',f.today).values.planned,0);assert.equal(s.plans[0].estimated_minutes,100);await assert.rejects(f.db.query('select * from journal.routine_rules'),/permission denied/);await assert.rejects(f.call('create_routine',{...payload,startDate:'2026-02-30'}));await assert.rejects(f.call('create_plan',{...f.fields,startDate:null}));}finally{await f.db.close()}});
test('rule expansion and parent history are atomic; direct parent shrink must contain rule',async()=>{const f=await fixture();try{const draft={...f.draft,planId:f.planId,startDate:addDays(f.today,-1),endDate:addDays(f.today,8)};await f.call('create_routine',draft);let s=await f.snapshot();assert.equal(s.plans[0].start_date,draft.startDate);assert.equal(s.plans[0].end_date,draft.endDate);assert.equal(s.plans[0].history[0].previous_value.start_date,f.today);assert.equal(s.plans[0].history[0].previous_value.estimated_minutes,100);const before=s;await assert.rejects(f.call('update_plan',{...f.fields,planId:f.planId,endDate:addDays(f.today,3)}),/contain/);assert.deepEqual(await f.snapshot(),before);await f.call('update_plan',{...f.fields,planId:f.planId,startDate:draft.startDate,endDate:draft.endDate,title:'루틴 제목 변경'});assert.equal((await f.snapshot()).plans[0].history.length,2);}finally{await f.db.close()}});
test('future changes preserve past, complete, all execution history, exceptions and skipped dates',async()=>{const f=await fixture();try{const r=await f.call('create_routine',{...f.draft,planId:f.planId,startDate:addDays(f.today,-1)});let s=await f.snapshot();const at=(offset:number)=>s.tasks.find(t=>t.occurrence_date===addDays(f.today,offset))!;
 await f.call('set_task_complete',{taskId:at(1).id,complete:true});await f.call('update_task',{taskId:at(2).id,title:'이 날짜만',tags:['개별 태그']});const a=localInstant(addDays(f.today,3),'09:00'),b=localInstant(addDays(f.today,3),'09:10'),run=await f.call('create_run',{taskId:at(3).id,startedAt:a,endedAt:b,segments:[{kind:'work',startedAt:a,endedAt:b}]});await f.call('delete_entity',{entityType:'run',entityId:run.entityId});await f.call('skip_occurrence',{taskId:at(4).id});s=await f.snapshot();const protectedIds=[at(-1).id,at(1).id,at(2).id,at(3).id,at(4).id],before=s.tasks.filter(t=>protectedIds.includes(t.id));
 const value={...f.draft,routineId:r.entityId,title:'이후 새 제목',endDate:addDays(f.today,8),tags:['새 태그']},preview=routinePreview(s,s.routines?.[0],value as Parameters<typeof routinePreview>[2]);assert.equal(preview.protectedRows.length,4);assert.equal(preview.added,2);await f.call('update_routine',value);s=await f.snapshot();assert.deepEqual(s.tasks.filter(t=>protectedIds.includes(t.id)),before);assert.equal(s.tasks.find(t=>t.occurrence_date===f.today)?.title,'이후 새 제목');assert.equal(s.tasks.length,10);assert.equal(s.plans[0].end_date,addDays(f.today,8));assert.equal(s.routines?.[0].start_date,addDays(f.today,-1));
 await f.call('update_routine',{...value,endDate:addDays(f.today,1)});s=await f.snapshot();const cancelled=s.tasks.filter(t=>t.cancelled_at);assert.equal(cancelled.length,4);assert.equal(s.plans[0].end_date,addDays(f.today,8));await f.call('update_routine',value);s=await f.snapshot();assert.equal(s.tasks.length,10);assert.deepEqual(s.tasks.filter(t=>t.cancelled_at).map(t=>t.id),cancelled.map(t=>t.id));assert.equal(s.tasks.find(t=>t.id===at(2).id)?.tags[0].name,'개별 태그');
 }finally{await f.db.close()}});
test('fixed overlaps rollback parent, rule, tasks and receipt; explicit confirmation preserves exact time',async()=>{const f=await fixture();try{const payload={...f.draft,planId:f.planId,timing:'fixed',time:'09:03',endDate:addDays(f.today,7)},r=await f.call('create_routine',{...payload,endDate:addDays(f.today,6)}),before=await f.snapshot();await assert.rejects(f.call('create_routine',payload,id(80)),/overlap/);assert.deepEqual(await f.snapshot(),before);await f.call('create_routine',{...payload,allowOverlap:true},id(80));const s=await f.snapshot();assert.equal(s.routines?.length,2);assert.equal(Date.parse(s.placements[0].started_at),Date.parse(localInstant(f.today,'09:03')));await assert.rejects(f.call('update_task',{taskId:s.tasks[0].id,title:'날짜 수정 금지',dueDate:addDays(f.today,2)}),/date is fixed/);assert.ok(s.routines?.some(rule=>rule.id===r.entityId));}finally{await f.db.close()}});
test('skip and stop restore through trash without re-creating dates or reopening actual records',async()=>{const f=await fixture();try{const r=await f.call('create_routine',{...f.draft,planId:f.planId,timing:'fixed'});let s=await f.snapshot();const today=s.tasks.find(t=>t.occurrence_date===f.today)!;await f.call('skip_occurrence',{taskId:today.id});s=await f.snapshot();const skip=s.trash.find(t=>t.entity_type==='routine')!;assert.equal(s.tasks.find(t=>t.id===today.id)?.skipped,true);assert.equal(s.placements.length,6);await f.call('stop_routine',{routineId:r.entityId,fromDate:addDays(f.today,1)});s=await f.snapshot();const stop=s.trash.find(t=>t.id!==skip.id)!;assert.equal(s.tasks.filter(t=>t.cancelled_at).length,6);await f.call('restore_entity',{trashId:stop.id});await f.call('restore_entity',{trashId:skip.id});s=await f.snapshot();assert.equal(s.tasks.length,7);assert.equal(s.placements.length,7);assert.equal(s.tasks.filter(t=>t.skipped||t.cancelled_at).length,0);assert.equal(s.routines?.[0].stopped_from,null);await f.call('delete_entity',{entityType:'plan',entityId:f.planId});s=await f.snapshot();assert.equal(s.routines?.length,0);await f.call('restore_entity',{trashId:s.trash[0].id});s=await f.snapshot();assert.equal(s.routines?.length,1);assert.equal(s.tasks.length,7);}finally{await f.db.close()}});

test('overlapping restoration requires explicit confirmation and wrong types are rejected',async()=>{const f=await fixture();try{
 await f.call('create_routine',{...f.draft,planId:f.planId,timing:'fixed'});let s=await f.snapshot();const task=s.tasks.find(t=>t.occurrence_date===f.today)!;await f.call('skip_occurrence',{taskId:task.id});s=await f.snapshot();const trash=s.trash[0];
 const gp=await f.call('create_plan',{kind:'general',title:'별도 계획',startDate:f.today,endDate:f.today});const gt=await f.call('create_task',{planId:gp.entityId,title:'겹치는 할 일'});await f.call('create_placement',{taskId:gt.entityId,startedAt:localInstant(f.today,'09:00'),endedAt:localInstant(f.today,'09:20')});s=await f.snapshot();assert.equal(s.trash[0].placement_conflict,true);const before=s;await assert.rejects(f.call('restore_entity',{trashId:trash.id}),/overlap/);assert.deepEqual(await f.snapshot(),before);await assert.rejects(f.call('restore_entity',{trashId:trash.id,allowOverlap:'true'}),/Boolean/);await f.call('restore_entity',{trashId:trash.id,allowOverlap:true});assert.equal((await f.snapshot()).placements.length,8);
 }finally{await f.db.close()}});

test('routine execution survives deleting its plan and date-specific placement edits remain protected',async()=>{const f=await fixture();try{
 const r=await f.call('create_routine',{...f.draft,planId:f.planId}),s=await f.snapshot(),task=s.tasks[0],a=localInstant(f.today,'09:00'),b=localInstant(f.today,'09:15');await f.call('create_placement',{taskId:task.id,startedAt:a,endedAt:b});await f.call('update_routine',{...f.draft,routineId:r.entityId,title:'이후 변경'});assert.equal((await f.snapshot()).tasks.find(t=>t.id===task.id)?.title,'독서');await f.call('create_run',{taskId:task.id,startedAt:a,endedAt:b,segments:[{kind:'work',startedAt:a,endedAt:b}]});await f.call('save_thought',{taskId:task.id,date:f.today,body:'보존되는 단상'});await f.call('delete_entity',{entityType:'plan',entityId:f.planId});const after=await f.snapshot();assert.equal(after.routines?.length,0);assert.equal(after.runs.length,1);assert.equal(after.thoughts.length,1);assert.equal(dayItems(after,f.today).tasks[0].id,task.id);const exported=(await f.db.query<{v:{routines:unknown[]}}>('select public.haru_export() v')).rows[0].v;assert.equal(exported.routines.length,1);
 }finally{await f.db.close()}});


test('fixed preview detects long spanning placements but ignores touching boundaries',async()=>{const f=await fixture();try{const data=await f.snapshot(),date=addDays(f.today,3),draft={...f.draft,startDate:date,endDate:date,priority:'normal' as const,timing:'fixed' as const,time:'09:00'};data.placements=[{id:id(700),task_id:id(701),started_at:localInstant(f.today,'08:00'),ended_at:localInstant(addDays(f.today,6),'12:00')}];assert.equal(routinePreview(data,undefined,draft).conflicts.length,1);data.placements[0].ended_at=localInstant(date,'09:00');assert.equal(routinePreview(data,undefined,draft).conflicts.length,0);data.placements[0].started_at=localInstant(date,'09:20');data.placements[0].ended_at=localInstant(date,'10:00');assert.equal(routinePreview(data,undefined,draft).conflicts.length,0);}finally{await f.db.close()}});
