const records=await readFile(new URL('../supabase/migrations/0004_records_archive.sql',import.meta.url),'utf8');
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {DIARY_ID,parseCommand,validDate} from '../src/lib/contracts.ts';
const sql=await readFile(new URL('../supabase/migrations/0001_core.sql',import.meta.url),'utf8');
const schedule=await readFile(new URL('../supabase/migrations/0003_schedule_runs.sql',import.meta.url),'utf8');
const followup=await readFile(new URL('../supabase/migrations/0002_plan_priority_task_tags.sql',import.meta.url),'utf8');
async function setup(){const db=new PGlite();await db.exec('create role anon; create role authenticated; create role service_role;');await db.exec(sql);await db.exec(followup);await db.exec(schedule);await db.exec(records);return db;}
const req=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const plan={kind:'general',title:'검증 계획',startDate:'2026-09-17',endDate:'2026-09-30'};
async function command(db:PGlite,n:number,revision:number,name:string,payload:unknown){const r=await db.query<{result:{revision:number;entityId:string}}>('select public.journal_command($1,$2,$3,$4,$5::jsonb) result',[DIARY_ID,req(n),revision,name,JSON.stringify(payload)]);return r.rows[0].result;}
async function snapshot(db:PGlite){const r=await db.query<{data:{revision:number;plans:unknown[];tasks:{complete:boolean;completed_at:string|null}[]}}>('select public.journal_snapshot($1) data',[DIARY_ID]);return r.rows[0].data;}
test('SQL replays same request once and rejects changed contents or stale revision',async()=>{const db=await setup();try{const first=await command(db,1,0,'create_plan',plan);assert.deepEqual(await command(db,1,0,'create_plan',plan),first);assert.equal((await snapshot(db)).plans.length,1);await assert.rejects(command(db,1,0,'create_plan',{...plan,title:'다른 내용'}),/different content/);await assert.rejects(command(db,2,0,'create_plan',plan),/Revision conflict/);assert.equal((await snapshot(db)).revision,1);}finally{await db.close()}});
test('SQL invalid date range rolls back receipt and revision, valid retry succeeds',async()=>{const db=await setup();try{await assert.rejects(command(db,1,0,'create_plan',{...plan,endDate:'2026-09-01'}));assert.equal((await snapshot(db)).revision,0);assert.equal((await snapshot(db)).plans.length,0);await command(db,1,0,'create_plan',plan);assert.equal((await snapshot(db)).revision,1);}finally{await db.close()}});
test('SQL task completion persists, audits old state and missing parent is rejected',async()=>{const db=await setup();try{await assert.rejects(command(db,1,0,'create_task',{planId:req(999),title:'고아'}));const p=await command(db,2,0,'create_plan',plan);const t=await command(db,3,1,'create_task',{planId:p.entityId,title:'할 일',dueDate:'2026-09-20',estimatedMinutes:20});await command(db,4,2,'set_task_complete',{taskId:t.entityId,complete:true});let s=await snapshot(db);assert.equal(s.tasks[0].complete,true);assert.ok(s.tasks[0].completed_at);await command(db,5,3,'set_task_complete',{taskId:t.entityId,complete:false});s=await snapshot(db);assert.equal(s.tasks[0].completed_at,null);const history=await db.query<{n:number}>('select count(*)::int n from journal.revisions');assert.equal(history.rows[0].n,2);}finally{await db.close()}});
test('SQL same-diary revision serializes competing writes',async()=>{const db=await setup();try{const results=await Promise.allSettled([command(db,1,0,'create_plan',plan),command(db,2,0,'create_plan',{...plan,title:'다른 창'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await snapshot(db)).plans.length,1);}finally{await db.close()}});
test('anon cannot use RPC or read private tables; service role can use RPC',async()=>{const db=await setup();try{await db.exec('set role anon');await assert.rejects(snapshot(db),/permission denied/);await assert.rejects(db.query('select * from journal.plans'),/permission denied/);await db.exec('reset role;set role service_role');assert.equal((await snapshot(db)).revision,0);}finally{await db.close()}});
test('server validation rejects invalid dates, types and missing title',()=>{assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2024-02-29'),true);assert.throws(()=>parseCommand({requestId:req(1),expectedRevision:0,command:'create_plan',payload:{...plan,title:'   '}}));assert.throws(()=>parseCommand({requestId:req(1),expectedRevision:0,command:'set_task_complete',payload:{taskId:req(2),complete:'false'}}));assert.throws(()=>parseCommand({requestId:req(1),expectedRevision:-1,command:'create_plan',payload:plan}));});
