'use client';
import {useRef,useState} from 'react';
import {addDays,seoulDate} from '@/lib/schedule';
import {CalendarIcon} from './icons';
import {dateButtonText} from './presentation';
import {PickerDialog} from './picker-dialog';
export function DateField({label,value,onChange,required=false,min,max,compact=false,display}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;min?:string;max?:string;compact?:boolean;display?:string}){
 const [open,setOpen]=useState(false),[month,setMonth]=useState((value||seoulDate()).slice(0,7)),[jump,setJump]=useState(false),[jumpYear,setJumpYear]=useState(0),[jumpMonth,setJumpMonth]=useState(1);const button=useRef<HTMLButtonElement>(null);const [year,m]=month.split('-').map(Number),first=new Date(Date.UTC(year,m-1,1)).getUTCDay(),count=new Date(Date.UTC(year,m,0)).getUTCDate();
 function allowed(day:string){return !(min&&day<min||max&&day>max);}
 function select(day:string){if(day&&!allowed(day))return;onChange(day);setOpen(false);}
 function shift(delta:number){setMonth(new Date(Date.UTC(year,m-1+delta,1)).toISOString().slice(0,7));}
 const today=seoulDate();
 return <div className={compact?'date-field compact':'date-field field'}>{!compact&&<span>{label}</span>}<button type="button" ref={button} className={compact?'btn sm date-nav-button':'date-select-only'+(value?' has-value':'')} aria-label={label+' 달력 열기'} aria-haspopup="dialog" aria-expanded={open} onClick={()=>{if(value)setMonth(value.slice(0,7));setJump(false);setOpen(true);}}><span>{display||(value?dateButtonText(value):'날짜 선택')}</span><CalendarIcon/></button>{open&&<PickerDialog anchor={button} onClose={()=>setOpen(false)}><div className="date-dialog-head"><h2>{label} 선택</h2><button type="button" className="iconbtn" aria-label="날짜 선택 닫기" onClick={()=>setOpen(false)}>×</button></div><div className="date-calendar-nav"><button type="button" className="iconbtn" aria-label="이전 달" onClick={()=>shift(-1)}>‹</button><button className="month-jump-trigger" type="button" aria-label="연도와 월 바로 선택" onClick={()=>{setJump(!jump);setJumpYear(year);setJumpMonth(m);}}>{year}년 {m}월</button><button type="button" className="iconbtn" aria-label="다음 달" onClick={()=>shift(1)}>›</button></div>{jump?<div className="date-month-jump"><label>연도<input type="number" min={1000} max={9999} value={jumpYear} onChange={e=>setJumpYear(Number(e.target.value))}/></label><label>월<select value={jumpMonth} onChange={e=>setJumpMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1}월</option>)}</select></label><button className="btn sm" type="button" onClick={()=>{if(jumpYear>=1000&&jumpYear<=9999){setMonth(jumpYear+'-'+String(jumpMonth).padStart(2,'0'));setJump(false);}}}>이동</button></div>:<div className="date-picker-grid" role="group" aria-label="달력 날짜 선택">{[...'일월화수목금토'].map(d=><span className="calendar-weekday" key={d}>{d}</span>)}{Array.from({length:first},(_,i)=><span key={'empty'+i}/>)}{Array.from({length:count},(_,i)=>{const day=month+'-'+String(i+1).padStart(2,'0');return <button type="button" className={'calendar-day'+(day===today?' is-today':'')+(value===day?' is-selected':'')} key={day} aria-label={day} disabled={!allowed(day)} aria-pressed={value===day} onClick={()=>select(day)}><span className="date-number">{i+1}</span></button>;})}</div>}<div className="date-picker-shortcuts"><button type="button" className="btn sm" disabled={!allowed(today)} onClick={()=>select(today)}>오늘</button><button type="button" className="btn sm" disabled={!allowed(addDays(today,1))} onClick={()=>select(addDays(today,1))}>내일</button>{!required&&<button type="button" className="link" onClick={()=>select('')}>날짜 없음</button>}</div></PickerDialog>}</div>;
}
