'use client';
import type {Snapshot} from '@/lib/contracts';
import {monthEntriesForDay} from '@/lib/month-preview';
import {clockLabel,dayWindow} from '@/lib/schedule';
import {dateText,priorityText} from './presentation';
const weekdays=['일','월','화','수','목','금','토'];
export function Monthly({data,day,today,selectDay,openDay}:{data:Snapshot;day:string;today:string;selectDay:(d:string)=>void;openDay:(d:string,id?:string)=>void}){
 const first=day.slice(0,7)+'-01',lead=new Date(first+'T12:00:00Z').getUTCDay(),count=new Date(Date.UTC(Number(day.slice(0,4)),Number(day.slice(5,7)),0)).getUTCDate(),total=Math.ceil((lead+count)/7)*7,entries=monthEntriesForDay(data,day),{from,to}=dayWindow(day);
 return <><p className="small muted">날짜를 선택하면 이곳에서 할 일을 간략히 확인할 수 있습니다.</p><div className="calendar-grid month-overview">{weekdays.map(d=><div className="cal-head" key={d}>{d}</div>)}{Array.from({length:total},(_,i)=>{const num=i-lead+1;if(num<1||num>count)return <div key={i} aria-hidden="true"/>;const d=day.slice(0,7)+'-'+String(num).padStart(2,'0'),items=monthEntriesForDay(data,d);return <button className={(d===today?'current ':'')+(d===day?'selected-date':'')} key={d} aria-pressed={d===day} aria-label={dateText(d,true)+' · 할 일 '+items.length+'개'} onClick={()=>selectDay(d)}><span className="month-date"><span className="date-number" data-typo-role="number">{num}</span>{d===today&&<span className="month-today">오늘</span>}</span><span className="month-cell-items">{items.slice(0,2).map(({task},n)=><span className={'month-cell-title'+(n===1?' month-second':'')+(task.complete?' done':'')} data-typo-role="title" key={task.id}>{task.title}</span>)}</span>{items.length>2&&<small className="month-more-desktop">외 {items.length-2}개</small>}{items.length>1&&<small className="month-more-mobile">외 {items.length-1}개</small>}</button>;})}</div>
 <section className="month-preview" aria-label="선택 날짜의 할 일"><div className="row spread"><h2 data-typo-role="title">{dateText(day,true)}의 할 일</h2><button className="link" onClick={()=>openDay(day)}>일간 상세 →</button></div><p className="small muted">시간을 배치했거나 이날 마감인 할 일입니다. 루틴은 해당 날짜의 할 일을 표시합니다.</p>{entries.length?<ul>{entries.map(({task,placements,due})=><li key={task.id}><button className="month-preview-entry" onClick={()=>openDay(day,task.id)} aria-label={task.title+' 일간 상세'}><span className="month-preview-copy"><small>{data.plans.find(p=>p.id===task.plan_id)?.title||'지난 계획'}</small><strong data-typo-role="title">{task.title}</strong><span>{placements.length?placements.map(p=>clockLabel(Math.max(from,Date.parse(p.started_at)))+'–'+(Date.parse(p.ended_at)>=to?'다음 날 00:00':clockLabel(p.ended_at))).join(' · '):'시간 미정'}{due?' · 이날 마감':''} · {task.complete?'완료':'미완료'} · 우선순위 {priorityText(task.priority)}</span></span><span aria-hidden="true">→</span></button></li>)}</ul>:<p className="empty">이 날짜에 배치하거나 마감인 할 일이 없습니다.</p>}</section></>;
}
