'use client';
import {useEffect,useState} from 'react';
import type {Improvement,Plan,Priority,Task} from '@/lib/contracts';
import {visibleTasks,type TaskView} from '@/lib/task-view';
import {RunEditor} from './run-editor';
import {clockLabel,seoulDate} from '@/lib/schedule';
import {duration} from '@/lib/review';
import {useJournal} from './journal-provider';
import {RoutineRules} from './routines';
import {DateField} from './date-field';
import {DurationField,PriorityField} from './forms';
import {dateText,priorityText} from './presentation';
export function TaskEditor({task,planId,onSaved,onCancel}:{task?:Task;planId:string;onSaved:()=>void;onCancel:()=>void}){
 const {locked,send}=useJournal();const [draft,setDraft]=useState({title:task?.title||'',dueDate:task?.due_date||'',estimatedMinutes:task?.estimated_minutes??30,priority:task?.priority||'normal' as Priority,description:task?.description||'',tags:task?.tags.map(t=>t.name)||[] as string[]}),[tag,setTag]=useState(''),[error,setError]=useState('');
 function addTag(){const name=tag.trim();if(!name)return;if(draft.tags.length>=20&&!draft.tags.includes(name)){setError('태그는 최대 20개까지 입력할 수 있습니다.');return;}setDraft(v=>({...v,tags:[...new Set([...v.tags,name])]}));setTag('');}
 return <section className="editor"><div className="editor-head"><h2 data-typo-role="title">{task?'할 일 수정':'할 일 추가'}</h2><button className="btn sm" onClick={onCancel}>닫기</button></div><form onSubmit={async e=>{e.preventDefault();const tags=[...new Set([...draft.tags,...(tag.trim()?[tag.trim()]:[])])];if(await send(task?'update_task':'create_task',{...draft,tags,...(task?{taskId:task.id}:{planId})}))onSaved();}}><fieldset disabled={locked}><div className="formgrid"><label className="field wide"><span>할 일 제목</span><input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><DateField label="마감일" value={draft.dueDate} onChange={dueDate=>setDraft({...draft,dueDate})}/><DurationField label="할 일 예상 시간" value={draft.estimatedMinutes} onChange={estimatedMinutes=>setDraft({...draft,estimatedMinutes})}/><PriorityField value={draft.priority} onChange={priority=>setDraft({...draft,priority})}/></div>
 <details className="formextra"><summary>설명·태그</summary><div className="formgrid"><label className="field wide"><span>설명</span><textarea data-typo-role="record-input" maxLength={4000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="field wide"><span>태그</span><div className="row"><input maxLength={30} placeholder="태그 입력 후 Enter" value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();addTag();}}}/><button type="button" className="btn sm" onClick={addTag} disabled={!tag.trim()}>추가</button></div><div className="tag-chips">{draft.tags.map(name=><span className="pill" key={name}>{name}<button type="button" aria-label={name+' 태그 제거'} onClick={()=>setDraft({...draft,tags:draft.tags.filter(v=>v!==name)})}>×</button></span>)}</div><em>각 30자 이내, 최대 20개. 입력 중인 태그도 저장에 포함됩니다.</em></div></div></details>
 {error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="btn" onClick={onCancel}>취소</button><button type="submit" className="btn primary">{locked?'저장 중…':task?'변경 저장':'할 일 저장'}</button></div></fieldset></form>{task&&<TaskRecordZones task={task}/>}</section>;
}
function TaskRecordZones({task}:{task:Task}){const {data,locked}=useJournal();const [mode,setMode]=useState<'placement'|'run'|null>(null);const placements=data?.placements.filter(p=>p.task_id===task.id)||[],runs=data?.runs.filter(r=>r.task_id===task.id&&r.ended_at)||[];return <div className="task-edit-zone"><details><summary>시간 배치</summary><p className="small muted">{task.complete?'완료한 할 일은 새로 배치할 수 없습니다.':'시간표에 예정 시간을 배치합니다.'}</p>{placements.map(p=><p className="small muted" key={p.id}>{dateText(seoulDate(new Date(p.started_at)))} {clockLabel(p.started_at)}–{clockLabel(p.ended_at)}</p>)}<button className="btn sm" disabled={locked||task.complete} onClick={()=>setMode('placement')}>계획 배치</button></details><details><summary>실행 기록 · 수기 입력</summary><p className="small muted">완료한 할 일에도 실제로 한 시간을 입력할 수 있습니다.</p><button className="btn sm" disabled={locked} onClick={()=>setMode('run')}>실행 기록 입력</button></details><details><summary>실행 기록 이력 <span className="pill">{runs.length}건</span></summary>{runs.map(r=><div className="record-row" key={r.id}><strong data-typo-role="info">{dateText(seoulDate(new Date(r.started_at)))} {clockLabel(r.started_at)}–{clockLabel(r.ended_at!)}</strong><small>작업 {duration(Number(r.work_seconds)*1000)} · {r.source==='live'?'타이머 기록':'수기 기록'}</small>{r.blocked_reason&&<p data-typo-role="record">{r.blocked_reason}</p>}</div>)}{!runs.length&&<p className="small muted">종료한 실행 기록이 없습니다.</p>}</details>{mode&&<RunEditor task={task} day={seoulDate()} mode={mode} onClose={()=>setMode(null)}/>}</div>;}
function PlanEditor({value,onSaved,onCancel}:{value?:Plan;onSaved:(id:string)=>void;onCancel:()=>void}){
 const {locked,send}=useJournal();const [draft,setDraft]=useState({kind:value?.kind||'general' as 'general'|'routine',title:value?.title||'',startDate:value?.start_date||seoulDate(),endDate:value?.end_date||seoulDate(),successText:value?.success_text||'',estimatedMinutes:value?.estimated_minutes||0,priority:value?.priority||'normal' as Priority});
 return <section className="editor"><div className="editor-head"><h2 data-typo-role="title">{value?'계획 수정':'계획 만들기'}</h2><button className="btn sm" onClick={onCancel}>닫기</button></div><form onSubmit={async e=>{e.preventDefault();const saved=await send(value?'update_plan':'create_plan',{...draft,...(value?{planId:value.id}:{})});if(saved)onSaved(saved.entityId||value?.id||'');}}><fieldset disabled={locked}>{!value&&<div className="routine-choices" aria-label="계획 유형">{([['general','일반 계획'],['routine','↻ 루틴 계획']] as const).map(([kind,label])=><label key={kind}><input type="radio" name="plan-kind" checked={draft.kind===kind} onChange={()=>setDraft({...draft,kind})}/>{label}</label>)}</div>}<div className="formgrid"><label className="field wide"><span>계획 제목</span><input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><DateField label="시작일" required value={draft.startDate} onChange={startDate=>setDraft({...draft,startDate})}/><DateField label="종료일" required min={draft.startDate} value={draft.endDate} onChange={endDate=>setDraft({...draft,endDate})}/><label className="field wide"><span>성공 기준</span><textarea required maxLength={4000} data-typo-role="record-input" value={draft.successText} onChange={e=>setDraft({...draft,successText:e.target.value})}/></label><DurationField label="계획 전체 예상 시간" max={525600} value={draft.estimatedMinutes} onChange={estimatedMinutes=>setDraft({...draft,estimatedMinutes})}/><PriorityField value={draft.priority} onChange={priority=>setDraft({...draft,priority})}/></div><p className="form-help">계획 전체 예상과 할 일 예상 합계는 독립된 값입니다. 자동으로 서로 덮어쓰지 않습니다.</p><div className="form-actions"><button className="btn" type="button" onClick={onCancel}>취소</button><button className="btn primary">{locked?'저장 중…':'계획 저장'}</button></div></fieldset></form></section>;
}
export function Plans({editRequest='',onEditHandled=()=>{},openPlan='',planRequest=0}:{editRequest?:string;onEditHandled?:()=>void;openPlan?:string;planRequest?:number}){
 const {data,locked,blocked,send}=useJournal();const [planId,setPlanId]=useState(''),[planEditor,setPlanEditor]=useState<'new'|Plan|null>(null),[taskEditor,setTaskEditor]=useState<'new'|Task|null>(null),[view,setView]=useState<TaskView>({query:'',status:'all',tag:'',sort:'due'}),[error,setError]=useState('');
 useEffect(()=>{if(data&&!data.plans.some(p=>p.id===planId)){setPlanId(data.plans[0]?.id||'');setView(v=>({...v,tag:''}));}},[data,planId]);
 useEffect(()=>{if(openPlan&&data?.plans.some(p=>p.id===openPlan)){setPlanId(openPlan);setTaskEditor(null);setPlanEditor(null);}},[openPlan,planRequest]);
 useEffect(()=>{if(editRequest&&data){const task=data.tasks.find(t=>t.id===editRequest);if(task){setPlanId(task.plan_id);setTaskEditor(task);}onEditHandled();}},[editRequest,data,onEditHandled]);
 const selected=data?.plans.find(p=>p.id===planId),tasks=data?.tasks.filter(t=>t.plan_id===planId)||[],shown=visibleTasks(tasks,view),done=tasks.filter(t=>t.complete).length;
 async function remove(type:'plan'|'task',id:string){if(data?.runs.some(r=>!r.ended_at&&(type==='task'?r.task_id===id:tasks.some(t=>t.id===r.task_id)))){setError('진행 중인 기록을 먼저 종료해 주세요.');return;}if(window.confirm(type==='plan'?'계획과 소속 할 일·예정 배치를 휴지통으로 옮길까요? 실제 기록·단상·회고는 남습니다.':'이 할 일과 예정 배치를 휴지통으로 옮길까요? 실제 기록·단상·회고는 남습니다.'))await send('delete_entity',{entityType:type,entityId:id,at:new Date().toISOString()});}
 const form=taskEditor?<><TaskEditor key={taskEditor==='new'?'new':taskEditor.id} task={taskEditor==='new'?undefined:taskEditor} planId={planId} onSaved={()=>setTaskEditor(null)} onCancel={()=>setTaskEditor(null)}/>{taskEditor!=='new'&&<details className="task-edit-zone"><summary>삭제</summary><p className="small muted">실제 기록·단상·회고는 보존하며 할 일과 예정 배치를 휴지통으로 옮깁니다.</p><button className="btn sm danger" disabled={locked} onClick={()=>void remove('task',taskEditor.id)}>할 일 삭제</button></details>}</>:null;
 return <div className="content-surface"><div className="page-head"><div><div className="eyebrow">PLAN / 할 일을 준비하는 곳</div><h1 data-typo-role="title">{data&&!data.plans.length?'첫 계획 만들기':'계획'}</h1></div><button className="btn sm" disabled={!data||locked||!!planEditor||!!taskEditor} onClick={()=>setPlanEditor('new')}>새 계획</button></div>{error&&<p className="error" role="alert">{error}</p>}
 {data&&!data.plans.length&&!planEditor&&<section className="welcome"><h2 data-typo-role="title">지금 실제로 하고 있는 일 하나</h2><p>작은 계획부터 시작할 수 있습니다. 계획을 만든 다음 구체적인 할 일을 추가합니다.</p><button className="btn primary" onClick={()=>setPlanEditor('new')}>첫 계획 만들기</button></section>}
 {!!data?.plans.length&&<div className="plan-picker"><label><span className="sr-only">선택한 계획</span><select aria-label="계획 선택" disabled={locked||!!planEditor||!!taskEditor} value={planId} onChange={e=>{setPlanId(e.target.value);setView({...view,tag:''});}}>{data.plans.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div>}
 {selected&&<header className="plan-heading"><div className="row spread"><div className="grow"><div className="eyebrow">진행 중</div><h1 data-typo-role="title">{selected.title}{selected.kind==='routine'&&<span className="routine-badge">↻ 루틴</span>}</h1><p className="small muted">{selected.start_date?dateText(selected.start_date):'기간 없음'}–{selected.end_date?dateText(selected.end_date):''}{selected.kind==='general'&&<> · 할 일 <b>{done} / {tasks.length}</b> 완료</>}</p></div><button className="btn sm" disabled={locked||!!planEditor||!!taskEditor} onClick={()=>setPlanEditor(selected)}>계획 수정</button></div></header>}
 {planEditor&&<PlanEditor key={planEditor==='new'?'new':planEditor.id} value={planEditor==='new'?undefined:planEditor} onSaved={id=>{setPlanId(id);setPlanEditor(null);}} onCancel={()=>setPlanEditor(null)}/>}
 {selected&&(selected.kind==='routine'?<RoutineRules plan={selected}/>:<section aria-label="할 일 관리"><div className="section-heading"><h2 data-typo-role="title">할 일 <span className="small muted">{tasks.length}</span></h2><button className="btn primary" disabled={locked||!!taskEditor||!!planEditor} onClick={()=>setTaskEditor('new')}>할 일 추가</button></div>{taskEditor==='new'&&form}
 {!!tasks.length&&<><div className="tasktools"><label>검색<input type="search" placeholder="제목·설명 검색" value={view.query} onChange={e=>setView({...view,query:e.target.value})}/></label><label>상태<select value={view.status} onChange={e=>setView({...view,status:e.target.value as TaskView['status']})}><option value="all">전체</option><option value="active">미완료</option><option value="complete">완료</option></select></label><label>정렬<select value={view.sort} onChange={e=>setView({...view,sort:e.target.value as TaskView['sort']})}><option value="due">마감 가까운 순</option><option value="priority">우선순위순</option><option value="recent">최근 추가순</option></select></label></div><div className="row spread small muted"><span>{shown.length} / {tasks.length}개</span><details><summary>정렬 기준</summary><p className="tiny">같은 마감일은 우선순위 → 생성순 → ID 순입니다.<br/>완료 상태만 바꿔서는 현재 정렬 순서를 바꾸지 않습니다.</p></details></div></>}
 <div className="task-list">{shown.map(t=><div key={t.id}><article className={'task-row'+(t.complete?' done':'')+(taskEditor!=='new'&&taskEditor?.id===t.id?' selected':'')}><label className="task-check"><input type="checkbox" checked={t.complete} disabled={blocked} aria-label={t.title+' 완료 상태'} onChange={e=>void send('set_task_complete',{taskId:t.id,complete:e.target.checked})}/></label><button className="task-select" disabled={locked||!!planEditor} aria-expanded={taskEditor!=='new'&&taskEditor?.id===t.id} onClick={()=>setTaskEditor(taskEditor!=='new'&&taskEditor?.id===t.id?null:t)}><span className="task-title" data-typo-role="title">{t.title}</span><span className="task-meta">{t.due_date?dateText(t.due_date)+' 마감':'마감일 없음'} · 예상 {duration(t.estimated_minutes*60000)}{data!.runs.some(r=>r.task_id===t.id&&r.ended_at)?' · 실제 '+duration(data!.runs.filter(r=>r.task_id===t.id&&r.ended_at).reduce((n,r)=>n+Number(r.work_seconds)*1000,0)):''}</span></button><span className="task-rail">{t.complete?'완료':priorityText(t.priority)}<small className="plan-edit-hint">제목을 눌러 수정</small></span></article>{taskEditor!=='new'&&taskEditor?.id===t.id&&form}</div>)}{!shown.length&&<div className="empty"><p>{tasks.length?'검색·필터에 맞는 할 일이 없습니다.':'계획을 구체적인 할 일로 구분해 보세요.'}</p></div>}</div></section>)}
 {selected&&<div className="plan-sections"><details><summary>계획 상세 · 성공 기준과 전체 예상</summary><dl className="facts"><div><dt>계획 전체 예상</dt><dd>{duration(selected.estimated_minutes*60000)}</dd></div><div><dt>할 일 예상 합계</dt><dd>{duration(tasks.reduce((n,t)=>n+t.estimated_minutes,0)*60000)}</dd></div><div><dt>우선순위</dt><dd>{priorityText(selected.priority)}</dd></div><div><dt>계획 ID</dt><dd>{selected.id}</dd></div><div className="wide"><dt>성공 기준</dt><dd data-typo-role="record">{selected.success_text}</dd></div></dl><p className="tiny muted">계획 전체 예상과 할 일 예상 합계는 독립된 값입니다. 자동으로 서로 덮어쓰지 않습니다.</p></details><details><summary>처음 계획 · 수정 이력 <span className="pill">{selected.history.length+1}개 버전</span></summary>{[...selected.history].reverse().map((v,i)=><div className="history-row" key={v.id}><b>{i===0?'처음 계획':'변경 전 계획'}</b><p data-typo-role="title">{v.previous_value.title} · {v.previous_value.start_date}–{v.previous_value.end_date} · {duration(v.previous_value.estimated_minutes*60000)}</p><p data-typo-role="record">{v.previous_value.success_text}</p></div>)}<div className="history-row"><b>{selected.history.length?'현재 계획':'처음 계획'}</b><p>{selected.title} · {selected.start_date}–{selected.end_date}</p></div></details>{!!data?.improvements.some(i=>i.target_plan_id===planId)&&<details className="incoming-improvements"><summary>이전 계획에서 가져온 개선점</summary>{data.improvements.filter(i=>i.target_plan_id===planId).map(i=><IncomingImprovement key={i.id} value={i}/>)}</details>}<details><summary>계획 삭제</summary><p className="small muted">계획과 소속 할 일·예정 배치를 휴지통으로 옮깁니다. 실제 기록·단상·회고는 보존합니다.</p><button className="btn sm danger" disabled={locked} onClick={()=>void remove('plan',selected.id)}>계획 삭제</button></details></div>}
 {!data&&<p className="empty">저장소에서 계획을 불러오고 있습니다.</p>}
 </div>;
}

function IncomingImprovement({value}:{value:Improvement}){const {data,locked,send}=useJournal(),[editing,setEditing]=useState(false),[body,setBody]=useState(value.body??value.source_text);return <article className="improvement-entry"><span className="improvement-source">{value.source_plan_title||data?.plans.find(p=>p.id===value.source_plan_id)?.title||'지난 계획'}에서 가져옴</span>{editing?<form onSubmit={async e=>{e.preventDefault();if(await send('update_improvement',{improvementId:value.id,body}))setEditing(false);}}><label className="field"><span>이 계획에서 바꿀 점</span><textarea data-typo-role="record-input" required maxLength={500} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="actions"><button className="btn sm" type="button" onClick={()=>setEditing(false)}>취소</button><button className="btn primary sm" disabled={locked}>변경 저장</button></div></form>:<><p data-typo-role="record">{value.body??value.source_text}</p><button className="btn sm" disabled={locked||!data?.improvementEditing} title={data?.improvementEditing?'원본 문장은 유지하며 이 계획의 문장만 수정':'서버에 개선점 편집 기능을 적용한 뒤 사용할 수 있습니다.'} onClick={()=>{setBody(value.body??value.source_text);setEditing(true);}}>수정</button></>}<details className="improvement-history"><summary data-typo-role="label">가져온 원문 · 수정 이력</summary><p data-typo-role="record">{value.source_text}</p>{value.history?.map(h=><div className="history-row" key={h.id}><small>{dateText(seoulDate(new Date(h.changed_at)))}</small><p data-typo-role="record">{h.previous_value.body}</p></div>)}</details></article>;}
