'use client';
import {useRef,useState} from 'react';
import type {Command,Snapshot} from '@/lib/contracts';
import {DateField} from './date-field';
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
export function Plans({initial,issue}:{initial:Snapshot|null;issue:string|null}){
 const [data,setData]=useState(initial),[error,setError]=useState(issue||''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[uncertain,setUncertain]=useState(false);
 const [planId,setPlanId]=useState(initial?.plans[0]?.id||''),[adding,setAdding]=useState(false),[taskAdding,setTaskAdding]=useState(false);
 const [plan,setPlan]=useState({title:'',startDate:today(),endDate:today(),successText:'',estimatedMinutes:0});
 const [task,setTask]=useState({title:'',dueDate:'',estimatedMinutes:30,priority:'normal',description:''});
 const pending=useRef<{signature:string;envelope:Command}|null>(null);
 async function refresh(){const response=await fetch('/api/diary',{cache:'no-store',signal:AbortSignal.timeout(15000)});const value=await response.json();if(!response.ok)throw Error(value.error?.message||'자료를 불러오지 못했습니다.');setData(value);return value as Snapshot;}
 async function send(command:Command['command'],payload:Record<string,unknown>){if(!data||busy||conflict)return false;setBusy(true);setError('');setMessage('');const signature=JSON.stringify({command,payload});if(pending.current&&pending.current.signature!==signature){setError('이전 저장 결과를 먼저 확인해야 합니다. 같은 내용으로 다시 저장해 주세요.');setBusy(false);return false;}const envelope=pending.current?.envelope||{requestId:crypto.randomUUID(),expectedRevision:data.revision,command,payload};pending.current={signature,envelope};let committed=false;try{const response=await fetch('/api/commands',{method:'POST',signal:AbortSignal.timeout(15000),headers:{'Content-Type':'application/json'},body:JSON.stringify(envelope)});const value=await response.json();if(!response.ok){if(response.status===409){setConflict(true);pending.current=null;}else if(response.status<500)pending.current=null;throw Error(value.error?.message||'저장하지 못했습니다.');}committed=true;pending.current=null;setData(previous=>previous?{...previous,revision:value.revision}:previous);await refresh();setUncertain(false);if(command==='create_plan'){setAdding(false);setPlan(v=>({...v,title:'',successText:''}));setPlanId(value.entityId);}if(command==='create_task'){setTaskAdding(false);setTask(v=>({...v,title:'',description:''}));}setMessage('저장했습니다.');return true;}catch(e){setError(committed?'저장은 완료됐지만 화면을 새로 불러오지 못했습니다. 최신 자료 확인을 눌러 주세요.':e instanceof Error?e.message:'연결을 확인하고 같은 내용으로 다시 시도해 주세요.');if(committed){setConflict(true);setUncertain(false);if(command==='create_plan')setAdding(false);if(command==='create_task')setTaskAdding(false);}else setUncertain(!!pending.current);return committed;}finally{setBusy(false)}}
 async function reload(){setBusy(true);try{await refresh();setConflict(false);setError('');setMessage('최신 자료를 불러왔습니다. 입력한 내용은 유지됩니다.');}catch(e){setError(e instanceof Error?e.message:'연결을 확인해 주세요.')}finally{setBusy(false)}}
 const selected=data?.plans.find(p=>p.id===planId),tasks=data?.tasks.filter(t=>t.plan_id===planId)||[];
 return <><div className="page-title"><div><small>PLAN</small><h2>계획</h2></div><button disabled={!data||busy} onClick={()=>setAdding(!adding)}>새 계획</button></div><p className="build-status">첫 구현 단계 · 일반 계획과 할 일 저장부터 연결하고 있습니다.</p>{error&&<div className="notice" role="alert">{error}<button disabled={busy} onClick={reload}>최신 자료 확인</button>{uncertain&&<button disabled={busy} onClick={()=>{const request=pending.current;if(request)void send(request.envelope.command,request.envelope.payload)}}>이전 저장 결과 확인</button>}</div>}{message&&<p role="status">{message}</p>}{uncertain&&!error&&<div className="notice" role="status">저장 결과 확인이 필요합니다.<button disabled={busy} onClick={()=>{const request=pending.current;if(request)void send(request.envelope.command,request.envelope.payload)}}>이전 저장 결과 확인</button></div>}{!data&&<section className="empty"><h3>저장소 연결을 준비하고 있습니다.</h3><p>연결 후 계획을 만들고 같은 자료를 다른 기기에서도 확인할 수 있습니다.</p></section>}
 {adding&&<form className="editor" onSubmit={async e=>{e.preventDefault();if(await send('create_plan',{kind:'general',...plan})){setAdding(false);setPlan({...plan,title:'',successText:''})}}}><h3>계획 만들기</h3><fieldset disabled={busy||conflict||uncertain}><label>계획 제목<input required maxLength={120} value={plan.title} onChange={e=>setPlan({...plan,title:e.target.value})}/></label><div className="form-grid"><DateField label="시작일" required value={plan.startDate} onChange={startDate=>setPlan({...plan,startDate})}/><DateField label="종료일" required value={plan.endDate} onChange={endDate=>setPlan({...plan,endDate})}/></div><label>이루고 싶은 것<textarea maxLength={4000} value={plan.successText} onChange={e=>setPlan({...plan,successText:e.target.value})}/></label><div className="actions"><button type="button" onClick={()=>setAdding(false)}>닫기</button><button className="primary" type="submit">{busy?'저장 중…':'계획 저장'}</button></div></fieldset></form>}
 {!!data?.plans.length&&<><label className="plan-picker">계획 선택<select value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">선택하세요</option>{data.plans.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{selected&&<><section className="plan-heading"><h3>{selected.title}</h3><p>{selected.start_date} — {selected.end_date}</p>{selected.success_text&&<p>{selected.success_text}</p>}</section><div className="section-heading"><h3>할 일 <small>{tasks.length}</small></h3><button disabled={busy} onClick={()=>setTaskAdding(!taskAdding)}>할 일 추가</button></div>{taskAdding&&<form className="editor" onSubmit={async e=>{e.preventDefault();if(await send('create_task',{...task,planId})){setTaskAdding(false);setTask({...task,title:'',description:''})}}}><fieldset disabled={busy||conflict||uncertain}><label>할 일 제목<input required maxLength={120} value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/></label><div className="form-grid"><DateField label="마감일" value={task.dueDate} onChange={dueDate=>setTask({...task,dueDate})}/><label>예상 시간 · 분<input type="number" min={0} max={10080} required value={task.estimatedMinutes} onChange={e=>setTask({...task,estimatedMinutes:Number(e.target.value)})}/></label><label>우선순위<select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option value="high">높음</option><option value="normal">보통</option><option value="low">낮음</option></select></label></div><label>설명<textarea maxLength={4000} value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/></label><div className="actions"><button type="button" onClick={()=>setTaskAdding(false)}>닫기</button><button type="submit" className="primary">할 일 저장</button></div></fieldset></form>}<div className="task-list">{tasks.map(t=><article key={t.id} className="task-row"><input type="checkbox" checked={t.complete} disabled={busy||conflict||uncertain} aria-label={t.title+' 완료'} onChange={e=>void send('set_task_complete',{taskId:t.id,complete:e.target.checked})}/><div><strong>{t.title}</strong><p>{t.due_date||'마감일 없음'} · 예상 {t.estimated_minutes}분 · {t.priority==='high'?'높음':t.priority==='low'?'낮음':'보통'}</p>{t.description&&<p>{t.description}</p>}</div><span>{t.complete?'완료':''}</span></article>)}{!tasks.length&&<p className="empty">할 일을 추가해 계획을 구체화해 보세요.</p>}</div></>}</>}
 {data&&!data.plans.length&&!adding&&<p className="empty">첫 계획을 만들어 보세요.</p>}</>;
}

