'use client';
import {ChoiceSelect} from './choice-select';
import {useEffect,useRef,useState} from 'react';
import type {Improvement,Plan,Priority,Task} from '@/lib/contracts';
import {visibleTasks,type TaskView} from '@/lib/task-view';
import {RunEditor} from './run-editor';
import {clockLabel,seoulDate} from '@/lib/schedule';
import {duration} from '@/lib/review';
import {useJournal} from './journal-provider';
import {useConfirm} from './confirm-dialog';
import {RoutineRules} from './routines';
import {DateField} from './date-field';
import {DurationField,PriorityField} from './forms';
import {dateText,priorityText} from './presentation';
import {planCompletion,planStatus,planStatusLabel} from '@/lib/calendar-plans';
import type {Snapshot} from '@/lib/contracts';
const markerNames={warm:'산호',gold:'황금',mint:'민트',blue:'푸른색',violet:'보라'} as const;
type MarkerColor=keyof typeof markerNames;
function PlanBrowser({data,selectedId,onSelect,disabled,study=false}:{data:Snapshot;selectedId:string;onSelect:(id:string)=>void;disabled:boolean;study?:boolean}){
 const [query,setQuery]=useState(''),[counts,setCounts]=useState<Record<string,number>>({active:8,overdue:8,finished:8,search:12}),[openGroups,setOpenGroups]=useState<Record<string,boolean>>({active:true});
 const needle=query.trim().toLocaleLowerCase('ko'),today=seoulDate();
 const groups=[
  {key:'active',label:'진행 중',plans:data.plans.filter(p=>planStatus(data,p,today)==='active')},
  {key:'overdue',label:'기한 경과',plans:data.plans.filter(p=>planStatus(data,p,today)==='overdue')},
  {key:'finished',label:'마친 계획',plans:data.plans.filter(p=>['completed','closed'].includes(planStatus(data,p,today)))}
 ];
 const row=(plan:Plan)=>{const count=planCompletion(data,plan);return <button type="button" className={'plan-browser-row'+(selectedId===plan.id?' selected':'')} key={plan.id} disabled={disabled} aria-current={selectedId===plan.id?'true':undefined} onClick={()=>onSelect(plan.id)}><span className="plan-browser-title" data-typo-role="title">{plan.title}</span><span className="plan-browser-meta">{plan.start_date?dateText(plan.start_date):'기간 없음'}–{plan.end_date?dateText(plan.end_date):''} · {count.done}/{count.total} 완료 · {planStatusLabel(planStatus(data,plan,today))}</span></button>};
 const results=data.plans.filter(p=>p.title.toLocaleLowerCase('ko').includes(needle));
 const limit=(key:string,list:Plan[])=>study?list.slice(0,counts[key]||8):list;
 const more=(key:string,total:number)=>study&&total>(counts[key]||8)?<button type="button" className="btn sm plan-browser-more" onClick={()=>setCounts(v=>({...v,[key]:(v[key]||8)+8}))}>계획 더 보기 · {total-(counts[key]||8)}개 남음</button>:null;
 return <section className="plan-browser" aria-label="계획 찾기">{study&&<h2 className="plan-browser-heading" data-typo-role="title">전체 계획 찾기</h2>}<label className="plan-browser-search"><span className="sr-only">계획 검색</span><input type="search" placeholder={study?'계획 검색':'계획 이름 검색'} value={query} onChange={e=>setQuery(e.target.value)}/></label>{needle?<><div className="plan-browser-results">{limit('search',results).map(row)}{!results.length&&<p className="small muted">검색 결과가 없습니다.</p>}</div>{more('search',results.length)}</>:groups.map(group=>group.plans.length?study?<details className="plan-browser-group" data-group={group.key} key={group.key} open={openGroups[group.key]??group.plans.some(p=>p.id===selectedId)} onToggle={e=>{const isOpen=e.currentTarget.open;setOpenGroups(v=>v[group.key]===isOpen?v:{...v,[group.key]:isOpen});}}><summary>{group.label} <span>{group.plans.length}</span></summary><div className="plan-browser-results">{limit(group.key,group.plans).map(row)}</div>{more(group.key,group.plans.length)}</details>:group.key==='active'?<div className="plan-browser-group" key={group.key}><h2>{group.label} <span>{group.plans.length}</span></h2><div className="plan-browser-results">{limit(group.key,group.plans).map(row)}</div>{more(group.key,group.plans.length)}</div>:<details className="plan-browser-group" key={group.key} open={group.plans.some(p=>p.id===selectedId)?true:undefined}><summary>{group.label} <span>{group.plans.length}</span></summary><div className="plan-browser-results">{limit(group.key,group.plans).map(row)}</div>{more(group.key,group.plans.length)}</details>:null)}</section>;
}
function PlanQuickPicker({data,selectedId,onSelect}:{data:Snapshot;selectedId:string;onSelect:(id:string)=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),search=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(open)search.current?.focus();},[open]);
 useEffect(()=>{if(!open)return;function outside(event:PointerEvent){if(!root.current?.contains(event.target as Node)){setOpen(false);setQuery('');}}document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside);},[open]);
 const today=seoulDate(),selected=data.plans.find(p=>p.id===selectedId),needle=query.trim().toLocaleLowerCase('ko');
 const matches=needle?data.plans.filter(p=>p.title.toLocaleLowerCase('ko').includes(needle)):data.plans.filter(p=>planStatus(data,p,today)==='active');
 const visible=matches.slice(0,needle?12:5);
 function close(restoreFocus=false){setOpen(false);setQuery('');if(restoreFocus)trigger.current?.focus();}
 function choose(id:string){onSelect(id);close(true);}
 return <div ref={root} className="study-plan-picker" onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))close();}}><span>현재 계획</span><button type="button" ref={trigger} aria-label={(selected?.title||'선택한 계획')+'에서 다른 계획 선택'} aria-expanded={open} aria-haspopup="dialog" onClick={()=>open?close():setOpen(true)}>계획 바꾸기 <span aria-hidden="true">⌄</span></button>{open&&<div className="study-plan-popover" role="dialog" aria-label="계획 선택" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();close(true);}}}><label>계획 검색<input ref={search} type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="제목으로 찾기"/></label><div className="study-plan-options">{visible.map(p=><button key={p.id} type="button" aria-current={p.id===selectedId?'true':undefined} onClick={()=>choose(p.id)}><strong>{p.title}</strong><small>{planStatusLabel(planStatus(data,p,today))} · {planCompletion(data,p).done}/{planCompletion(data,p).total} 완료</small></button>)}{!visible.length&&<p>일치하는 계획이 없습니다.</p>}{matches.length>visible.length&&<p>검색어를 더 입력하거나 아래의 전체 계획 목록에서 찾을 수 있습니다.</p>}</div><button type="button" className="link" onClick={()=>{close();document.querySelector('.study-plan-page .plan-browser')?.scrollIntoView({block:'start',behavior:'smooth'});}}>전체 계획 목록으로 ↓</button></div>}</div>;
}
function PlanMarkerEditor({plan}:{plan:Plan}){
 const {locked,send}=useJournal(),[color,setColor]=useState<MarkerColor>((plan.marker_color||'warm') as MarkerColor);
 return <div className="plan-marker-editor"><label className="field"><span>월간 형광펜 색</span><ChoiceSelect value={color} disabled={locked} onChange={e=>setColor(e.target.value as MarkerColor)}>{(Object.keys(markerNames) as MarkerColor[]).map(key=><option value={key} key={key}>{markerNames[key]}</option>)}</ChoiceSelect></label><button type="button" className="btn sm" disabled={locked||color===plan.marker_color} onClick={()=>void send('set_plan_marker',{planId:plan.id,markerColor:color})}>색 저장</button><p className="small muted">새 계획은 다섯 색을 순서대로 배정합니다. 이 선택은 월간에서만 사용합니다.</p></div>;
}
export function TaskEditor({task,planId,onSaved,onCancel}:{task?:Task;planId:string;onSaved:()=>void;onCancel:()=>void}){
 const {locked,send}=useJournal();const [draft,setDraft]=useState({title:task?.title||'',dueDate:task?.due_date||'',estimatedMinutes:task?.estimated_minutes??30,priority:task?.priority||'normal' as Priority,description:task?.description||'',tags:task?.tags.map(t=>t.name)||[] as string[]}),[tag,setTag]=useState(''),[error,setError]=useState('');
 function addTag(){const name=tag.trim();if(!name)return;if(draft.tags.length>=20&&!draft.tags.includes(name)){setError('태그는 최대 20개까지 입력할 수 있습니다.');return;}setDraft(v=>({...v,tags:[...new Set([...v.tags,name])]}));setTag('');}
 return <section className="editor"><div className="editor-head"><h2 data-typo-role="title">{task?'할 일 수정':'할 일 추가'}</h2><button className="btn sm" onClick={onCancel}>닫기</button></div><form onSubmit={async e=>{e.preventDefault();const tags=[...new Set([...draft.tags,...(tag.trim()?[tag.trim()]:[])])];if(await send(task?'update_task':'create_task',{...draft,tags,...(task?{taskId:task.id}:{planId})}))onSaved();}}><fieldset disabled={locked}><div className="formgrid"><label className="field wide"><span>할 일 제목</span><input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><DateField label="마감일" value={draft.dueDate} onChange={dueDate=>setDraft({...draft,dueDate})}/><DurationField label="할 일 예상 시간" value={draft.estimatedMinutes} onChange={estimatedMinutes=>setDraft({...draft,estimatedMinutes})}/><PriorityField value={draft.priority} onChange={priority=>setDraft({...draft,priority})}/></div>
 <details className="formextra"><summary>설명·태그</summary><div className="formgrid"><label className="field wide"><span>설명</span><textarea data-typo-role="record-input" maxLength={4000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="field wide"><span>태그</span><div className="row"><input maxLength={30} placeholder="태그 입력 후 Enter" value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();addTag();}}}/><button type="button" className="btn sm" onClick={addTag} disabled={!tag.trim()}>추가</button></div><div className="tag-chips">{draft.tags.map(name=><span className="pill" key={name}>{name}<button type="button" aria-label={name+' 태그 제거'} onClick={()=>setDraft({...draft,tags:draft.tags.filter(v=>v!==name)})}>×</button></span>)}</div><em>각 30자 이내, 최대 20개. 입력 중인 태그도 저장에 포함됩니다.</em></div></div></details>
 {error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="btn" onClick={onCancel}>취소</button><button type="submit" className="btn primary">{locked?'저장 중…':task?'변경 저장':'할 일 저장'}</button></div></fieldset></form>{task&&<TaskRecordZones task={task}/>}</section>;
}
function TaskRecordZones({task}:{task:Task}){
 const {data,locked}=useJournal(),[mode,setMode]=useState<'placement'|'run'|null>(null);
 const placements=data?.placements.filter(p=>p.task_id===task.id)||[],runs=data?.runs.filter(r=>r.task_id===task.id&&r.ended_at)||[];
 const closed=!!data?.plans.find(p=>p.id===task.plan_id)?.closed_at;
 return <div className="task-edit-zone"><details><summary>시간 배치</summary><p className="small muted">{closed?'종료한 계획은 다시 연 뒤 새로 배치할 수 있습니다.':task.complete?'완료한 할 일은 새로 배치할 수 없습니다.':'시간표에 예정 시간을 배치합니다.'}</p>{placements.map(p=><p className="small muted" key={p.id}>{dateText(seoulDate(new Date(p.started_at)))} {clockLabel(p.started_at)}–{clockLabel(p.ended_at)}</p>)}<button className="btn sm" disabled={locked||task.complete||closed} onClick={()=>setMode('placement')}>계획 배치</button>{mode==='placement'&&!closed&&<RunEditor task={task} day={seoulDate()} mode="placement" onClose={()=>setMode(null)}/>}</details><details><summary>실행 기록 · 수기 입력</summary><p className="small muted">완료·종료한 계획에도 과거 실제 시간을 입력하거나 고칠 수 있습니다.</p><button className="btn sm" disabled={locked} onClick={()=>setMode('run')}>실행 기록 입력</button>{mode==='run'&&<RunEditor task={task} day={seoulDate()} mode="run" onClose={()=>setMode(null)}/>}</details><details><summary>실행 기록 이력 <span className="pill">{runs.length}건</span></summary>{runs.map(r=><div className="record-row" key={r.id}><strong data-typo-role="info">{dateText(seoulDate(new Date(r.started_at)))} {clockLabel(r.started_at)}–{clockLabel(r.ended_at!)}</strong><small>작업 {duration(Number(r.work_seconds)*1000)} · {r.source==='live'?'타이머 기록':'수기 기록'}</small>{r.blocked_reason&&<p data-typo-role="record">{r.blocked_reason}</p>}</div>)}{!runs.length&&<p className="small muted">종료한 실행 기록이 없습니다.</p>}</details></div>;
}
function PlanEditor({value,onSaved,onCancel,showTitle=true}:{value?:Plan;onSaved:(id:string)=>void;onCancel:()=>void;showTitle?:boolean}){
 const {locked,send}=useJournal();const [draft,setDraft]=useState({kind:value?.kind||'general' as 'general'|'routine',title:value?.title||'',startDate:value?.start_date||seoulDate(),endDate:value?.end_date||seoulDate(),successText:value?.success_text||'',estimatedMinutes:value?.estimated_minutes||0,priority:value?.priority||'normal' as Priority});
 return <section className="editor">{showTitle&&<div className="editor-head"><h2 data-typo-role="title">{value?'계획 수정':'계획 만들기'}</h2><button className="btn sm" onClick={onCancel}>닫기</button></div>}<form onSubmit={async e=>{e.preventDefault();const saved=await send(value?'update_plan':'create_plan',{...draft,...(value?{planId:value.id}:{})});if(saved)onSaved(saved.entityId||value?.id||'');}}><fieldset disabled={locked}>{!value&&<div className="routine-choices" aria-label="계획 유형">{([['general','일반 계획'],['routine','↻ 루틴 계획']] as const).map(([kind,label])=><label key={kind}><input type="radio" name="plan-kind" checked={draft.kind===kind} onChange={()=>setDraft({...draft,kind})}/>{label}</label>)}</div>}<div className="formgrid"><label className="field wide"><span>계획 제목</span><input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><DateField label="시작일" required value={draft.startDate} onChange={startDate=>setDraft({...draft,startDate})}/><DateField label="종료일" required min={draft.startDate} value={draft.endDate} onChange={endDate=>setDraft({...draft,endDate})}/><label className="field wide"><span>성공 기준</span><textarea required maxLength={4000} data-typo-role="record-input" value={draft.successText} onChange={e=>setDraft({...draft,successText:e.target.value})}/></label><DurationField label="계획 전체 예상 시간" max={525600} value={draft.estimatedMinutes} onChange={estimatedMinutes=>setDraft({...draft,estimatedMinutes})}/><PriorityField value={draft.priority} onChange={priority=>setDraft({...draft,priority})}/></div><p className="form-help">계획 전체 예상과 할 일 예상 합계는 독립된 값입니다. 자동으로 서로 덮어쓰지 않습니다.</p><div className="form-actions"><button className="btn" type="button" onClick={onCancel}>취소</button><button className="btn primary">{locked?'저장 중…':'계획 저장'}</button></div></fieldset></form></section>;
}
export function Plans({editRequest='',onEditHandled=()=>{},openPlan='',planRequest=0,study=false}:{editRequest?:string;onEditHandled?:()=>void;openPlan?:string;planRequest?:number;study?:boolean}){
 const {data,locked,blocked,send}=useJournal(),confirm=useConfirm();const [planId,setPlanId]=useState(''),[planEditor,setPlanEditor]=useState<'new'|Plan|null>(null),[taskEditor,setTaskEditor]=useState<'new'|Task|null>(null),[view,setView]=useState<TaskView>({query:'',status:'all',tag:'',sort:'due'}),[error,setError]=useState('');
  useEffect(()=>{if(data&&!data.plans.some(p=>p.id===planId)){setPlanId(data.plans.find(p=>planStatus(data,p,seoulDate())==='active')?.id||data.plans[0]?.id||'');setView(v=>({...v,tag:''}));}},[data,planId]);
 useEffect(()=>{if(openPlan&&data?.plans.some(p=>p.id===openPlan)){setPlanId(openPlan);setTaskEditor(null);setPlanEditor(null);}},[openPlan,planRequest]);
 useEffect(()=>{if(editRequest&&data){const task=data.tasks.find(t=>t.id===editRequest);if(task){setPlanId(task.plan_id);setTaskEditor(task);}onEditHandled();}},[editRequest,data,onEditHandled]);
 const selected=data?.plans.find(p=>p.id===planId),tasks=data?.tasks.filter(t=>t.plan_id===planId)||[],shown=visibleTasks(tasks,view),done=tasks.filter(t=>t.complete).length;
 async function remove(type:'plan'|'task',id:string){if(data?.runs.some(r=>!r.ended_at&&(type==='task'?r.task_id===id:tasks.some(t=>t.id===r.task_id)))){setError('진행 중인 기록을 먼저 종료해 주세요.');return;}if(await confirm({title:type==='plan'?'계획을 삭제할까요?':'할 일을 삭제할까요?',description:type==='plan'?'계획과 소속 할 일·예정 배치를 휴지통으로 옮깁니다. 실제 기록·단상·회고는 남습니다.':'이 할 일과 예정 배치를 휴지통으로 옮깁니다. 실제 기록·단상·회고는 남습니다.',confirmLabel:type==='plan'?'계획 삭제':'할 일 삭제'}))await send('delete_entity',{entityType:type,entityId:id,at:new Date().toISOString()});}
 const form=taskEditor?<><TaskEditor key={taskEditor==='new'?'new':taskEditor.id} task={taskEditor==='new'?undefined:taskEditor} planId={planId} onSaved={()=>setTaskEditor(null)} onCancel={()=>setTaskEditor(null)}/>{taskEditor!=='new'&&<div className="row study-task-delete"><button className="btn sm danger" disabled={locked} onClick={()=>void remove('task',taskEditor.id)}>할 일 삭제</button></div>}</>:null;
  return <div className={'content-surface'+(study?' study-plan-page':'')}><div className="page-head"><div><div className="eyebrow">PLAN / 할 일을 준비하는 곳</div><h1 data-typo-role="title">{data&&!data.plans.length?'첫 계획 만들기':'계획'}</h1></div>{!study&&<button className="btn sm" disabled={!data||locked||!!planEditor||!!taskEditor} onClick={()=>setPlanEditor('new')}>새 계획</button>}</div>{error&&<p className="error" role="alert">{error}</p>}
  {study&&<section className="study-create-head"><div><h2 data-typo-role="title">새 계획 만들기</h2><p className="small muted">계획을 만든 뒤 그 안에 할 일을 추가합니다.</p></div><button className="btn primary" disabled={!data||locked||!!planEditor||!!taskEditor} onClick={()=>setPlanEditor('new')}>새 계획</button></section>}
 {study&&planEditor==='new'&&<div className="study-plan-editor-slot new"><PlanEditor key="plan-editor-new" showTitle={false} onSaved={id=>{setPlanId(id);setPlanEditor(null);}} onCancel={()=>setPlanEditor(null)}/></div>}
 {data&&!data.plans.length&&!planEditor&&<section className="welcome"><h2 data-typo-role="title">지금 실제로 하고 있는 일 하나</h2><p>작은 계획부터 시작할 수 있습니다. 계획을 만든 다음 구체적인 할 일을 추가합니다.</p><button className="btn primary" onClick={()=>setPlanEditor('new')}>첫 계획 만들기</button></section>}
  {!study&&!!data?.plans.length&&<PlanBrowser data={data} selectedId={planId} disabled={locked||!!planEditor||!!taskEditor} onSelect={id=>{setPlanId(id);setTaskEditor(null);setView({...view,tag:''});}}/>}
  {selected&&<header className="plan-heading"><div className="row spread"><div className="grow"><div className="eyebrow">{planStatusLabel(planStatus(data!,selected,seoulDate()))}</div>{study&&selected.kind==='general'?<label className="study-plan-close"><input type="checkbox" checked={!!selected.closed_at} disabled={locked||!!planEditor||!!taskEditor} aria-label={selected.title+' 계획 종료 상태'} onChange={e=>void send(e.target.checked?'close_plan':'reopen_plan',{planId:selected.id})}/><h1 data-typo-role="title">{selected.title}</h1></label>:<h1 data-typo-role="title">{selected.title}{selected.kind==='routine'&&<span className="routine-badge">↻ 루틴</span>}</h1>}<p className="small muted">{selected.start_date?dateText(selected.start_date):'기간 없음'}–{selected.end_date?dateText(selected.end_date):''}{selected.kind==='general'&&<> · 할 일 <b>{done} / {tasks.length}</b> 완료</>}</p>{study&&data&&<PlanQuickPicker data={data} selectedId={planId} onSelect={id=>{setPlanId(id);setTaskEditor(null);setView({...view,tag:''});}}/>}</div><div className="plan-action-buttons"><button className="btn sm" disabled={locked||!!planEditor||!!taskEditor} onClick={()=>setPlanEditor(selected)}>계획 수정</button>{study&&<button className="btn sm danger" disabled={locked||!!planEditor||!!taskEditor} onClick={()=>void remove('plan',selected.id)}>계획 삭제</button>}</div></div></header>}
  {selected?.kind==='general'&&!study&&<div className="plan-close-action"><p className="small muted">{selected.closed_at?'남은 할 일은 미완료로 보존됩니다. 지난 실행 기록은 계속 수정할 수 있습니다.':'할 일이 남아 있어도 계획을 종료할 수 있습니다. 완료 수는 실제 체크한 개수 그대로 유지됩니다.'}</p><button className="btn sm" disabled={locked||!!planEditor||!!taskEditor} onClick={()=>void send(selected.closed_at?'reopen_plan':'close_plan',{planId:selected.id})}>{selected.closed_at?'계획 다시 열기':'계획 종료'}</button></div>}
  {planEditor&&(!study||planEditor!=='new')&&<div className={study?'study-plan-editor-slot edit':'plan-editor-slot'}><PlanEditor key={planEditor==='new'?'plan-editor-new':'plan-editor-'+planEditor.id} value={planEditor==='new'?undefined:planEditor} onSaved={id=>{setPlanId(id);setPlanEditor(null);}} onCancel={()=>setPlanEditor(null)}/></div>}
 {planEditor&&planEditor!=='new'&&<PlanMarkerEditor key={'plan-marker-'+planEditor.id} plan={selected?.id===planEditor.id?selected:planEditor}/>}
 {selected&&(selected.kind==='routine'?<RoutineRules plan={selected}/>:<section aria-label="할 일 관리"><div className="section-heading"><h2 data-typo-role="title">할 일 <span className="small muted">{tasks.length}</span></h2><button className="btn primary" disabled={locked||!!taskEditor||!!planEditor||!!selected.closed_at} onClick={()=>setTaskEditor('new')}>할 일 추가</button></div>{taskEditor==='new'&&form}
 {!!tasks.length&&<><div className="tasktools"><label>검색<input type="search" placeholder="제목·설명 검색" value={view.query} onChange={e=>setView({...view,query:e.target.value})}/></label><label>상태<ChoiceSelect value={view.status} onChange={e=>setView({...view,status:e.target.value as TaskView['status']})}><option value="all">전체</option><option value="active">미완료</option><option value="complete">완료</option></ChoiceSelect></label><label>정렬<ChoiceSelect value={view.sort} onChange={e=>setView({...view,sort:e.target.value as TaskView['sort']})}><option value="due">마감 가까운 순</option><option value="priority">우선순위순</option><option value="recent">최근 추가순</option></ChoiceSelect></label></div><div className="row spread small muted"><span>{shown.length} / {tasks.length}개</span><details className="plan-sort-explainer"><summary>정렬 기준</summary><p className="tiny">같은 마감일은 우선순위 → 생성순 → ID 순입니다.<br/>완료 상태만 바꿔서는 현재 정렬 순서를 바꾸지 않습니다.</p></details></div></>}
 <div className="task-list">{shown.map(t=><div key={t.id}><article className={'task-row'+(t.complete?' done':'')+(taskEditor!=='new'&&taskEditor?.id===t.id?' selected':'')}><label className="task-check"><input type="checkbox" checked={t.complete} disabled={blocked} aria-label={t.title+' 완료 상태'} onChange={e=>void send('set_task_complete',{taskId:t.id,complete:e.target.checked})}/></label><button className="task-select" disabled={locked||!!planEditor} aria-expanded={taskEditor!=='new'&&taskEditor?.id===t.id} onClick={()=>setTaskEditor(taskEditor!=='new'&&taskEditor?.id===t.id?null:t)}><span className="task-title" data-typo-role="title">{t.title}</span><span className="task-meta">{t.due_date?dateText(t.due_date)+' 마감':'마감일 없음'} · 예상 {duration(t.estimated_minutes*60000)}{data!.runs.some(r=>r.task_id===t.id&&r.ended_at)?' · 실제 '+duration(data!.runs.filter(r=>r.task_id===t.id&&r.ended_at).reduce((n,r)=>n+Number(r.work_seconds)*1000,0)):''}</span></button><span className="task-rail">{t.complete?'완료':priorityText(t.priority)}<small className="plan-edit-hint">제목을 눌러 수정</small></span></article>{taskEditor!=='new'&&taskEditor?.id===t.id&&form}</div>)}{!shown.length&&<div className="empty"><p>{tasks.length?'검색·필터에 맞는 할 일이 없습니다.':'계획을 구체적인 할 일로 구분해 보세요.'}</p></div>}</div></section>)}
 {selected&&<div className="plan-sections"><details><summary>계획 상세 · 성공 기준과 전체 예상</summary><dl className="facts"><div><dt>계획 전체 예상</dt><dd>{duration(selected.estimated_minutes*60000)}</dd></div><div><dt>할 일 예상 합계</dt><dd>{duration(tasks.reduce((n,t)=>n+t.estimated_minutes,0)*60000)}</dd></div><div><dt>우선순위</dt><dd>{priorityText(selected.priority)}</dd></div><div><dt>계획 ID</dt><dd>{selected.id}</dd></div><div className="wide"><dt>성공 기준</dt><dd data-typo-role="record">{selected.success_text}</dd></div></dl><p className="tiny muted">계획 전체 예상과 할 일 예상 합계는 독립된 값입니다. 자동으로 서로 덮어쓰지 않습니다.</p></details><details><summary>처음 계획 · 수정 이력 <span className="pill">{selected.history.length+1}개 버전</span></summary>{[...selected.history].reverse().map((v,i)=><div className="history-row" key={v.id}><b>{i===0?'처음 계획':'변경 전 계획'}</b><p data-typo-role="title">{v.previous_value.title} · {v.previous_value.start_date}–{v.previous_value.end_date} · {duration(v.previous_value.estimated_minutes*60000)}</p><p data-typo-role="record">{v.previous_value.success_text}</p></div>)}<div className="history-row"><b>{selected.history.length?'현재 계획':'처음 계획'}</b><p>{selected.title} · {selected.start_date}–{selected.end_date}</p></div></details>{!!data?.improvements.some(i=>i.target_plan_id===planId)&&<details className="incoming-improvements"><summary>이전 계획에서 가져온 개선점</summary>{data.improvements.filter(i=>i.target_plan_id===planId).map(i=><IncomingImprovement key={i.id} value={i}/>)}</details>}</div>}
 {study&&!!data?.plans.length&&<PlanBrowser study data={data} selectedId={planId} disabled={locked||!!planEditor||!!taskEditor} onSelect={id=>{setPlanId(id);setTaskEditor(null);setView({...view,tag:''});}}/>}
 {!data&&<p className="empty">저장소에서 계획을 불러오고 있습니다.</p>}
 </div>;
}

function IncomingImprovement({value}:{value:Improvement}){const {data,locked,send}=useJournal(),[editing,setEditing]=useState(false),[body,setBody]=useState(value.body??value.source_text);return <article className="improvement-entry"><span className="improvement-source">{value.source_plan_title||data?.plans.find(p=>p.id===value.source_plan_id)?.title||'지난 계획'}에서 가져옴</span>{editing?<form onSubmit={async e=>{e.preventDefault();if(await send('update_improvement',{improvementId:value.id,body}))setEditing(false);}}><label className="field"><span>이 계획에서 바꿀 점</span><textarea data-typo-role="record-input" required maxLength={500} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="actions"><button className="btn sm" type="button" onClick={()=>setEditing(false)}>취소</button><button className="btn primary sm" disabled={locked}>변경 저장</button></div></form>:<><p data-typo-role="record">{value.body??value.source_text}</p><button className="btn sm" disabled={locked||!data?.improvementEditing} title={data?.improvementEditing?'원본 문장은 유지하며 이 계획의 문장만 수정':'서버에 개선점 편집 기능을 적용한 뒤 사용할 수 있습니다.'} onClick={()=>{setBody(value.body??value.source_text);setEditing(true);}}>수정</button></>}<details className="improvement-history"><summary data-typo-role="label">가져온 원문 · 수정 이력</summary><p data-typo-role="record">{value.source_text}</p>{value.history?.map(h=><div className="history-row" key={h.id}><small>{dateText(seoulDate(new Date(h.changed_at)))}</small><p data-typo-role="record">{h.previous_value.body}</p></div>)}</details></article>;}
