'use client';
import {useEffect,useRef,useState} from 'react';
import {runWork} from '@/lib/schedule';
import {useJournal} from './journal-provider';
const KEY='haru.t06.recording-panel.position.v1';
function MiniIcon({kind}:{kind:'grip'|'pause'|'play'|'stop'|'arrow'}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='grip'?<>{[5,12,19].flatMap(y=>[8,16].map(x=><circle cx={x} cy={y} r="1" key={x+':'+y}/>))}</>:kind==='pause'?<path d="M9 5v14M15 5v14"/>:kind==='play'?<path d="m8 5 11 7-11 7z"/>:kind==='stop'?<rect x="6" y="6" width="12" height="12" rx="1"/>:<path d="M5 12h14m-5-5 5 5-5 5"/>}</svg>;}
export function RecordingPanel({now,onOpen,visible=true}:{now:number;onOpen:(taskId:string)=>void;visible?:boolean}){
 const {data,locked,send}=useJournal(),run=data?.runs.find(r=>!r.ended_at),task=data?.tasks.find(t=>t.id===run?.task_id);
 const [position,setPosition]=useState<{x:number;y:number}|null>(null),[stop,setStop]=useState(false),[stopAt,setStopAt]=useState(''),[reason,setReason]=useState(''),[dragging,setDragging]=useState(false);const panel=useRef<HTMLElement>(null),safe=useRef<HTMLDivElement>(null),saved=useRef<{x:number;y:number}|null>(null),drag=useRef<{x:number;y:number;startX:number;startY:number}|null>(null);
 function bounds(){const r=safe.current?.getBoundingClientRect(),p=panel.current?.getBoundingClientRect();return {left:r?.left||14,top:r?.top||14,width:Math.max(0,(r?.width||window.innerWidth-28)-(p?.width||300)),height:Math.max(0,(r?.height||window.innerHeight-28)-(p?.height||76))};}
 function clamp(v:{x:number;y:number}){const b=bounds();return {x:Math.max(b.left,Math.min(b.left+b.width,v.x)),y:Math.max(b.top,Math.min(b.top+b.height,v.y))};}
 function persist(v:{x:number;y:number}){const b=bounds();saved.current={x:(v.x-b.left)/Math.max(1,b.width),y:(v.y-b.top)/Math.max(1,b.height)};try{localStorage.setItem(KEY,JSON.stringify(saved.current));}catch{}}
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=0&&p.y>=0&&p.x<=1&&p.y<=1)saved.current=p;}catch{}},[]);
 useEffect(()=>{function restore(){const b=bounds(),p=saved.current;setPosition(clamp({x:b.left+(p?p.x:1)*b.width,y:b.top+(p?p.y:1)*b.height}));}restore();window.addEventListener('resize',restore);return()=>window.removeEventListener('resize',restore);},[run?.id,visible]);
 if(!run||!task)return null;const paused=run.segments.at(-1)?.kind!=='work',minutes=Math.floor(runWork(run,undefined,undefined,stop?Date.parse(stopAt):now)/60000);
 return <><div id="recording-safe-area" ref={safe} aria-hidden="true"/><aside ref={panel} id="global-active" className={dragging?'is-dragging':''} hidden={!visible} aria-label="현재 기록" style={{position:'fixed',zIndex:90,...(position?{left:position.x,top:position.y,right:'auto',bottom:'auto'}:{right:14,bottom:14})}}><div className="record-mini-header"><button className="record-drag" title="드래그해서 이동 · 방향키로도 이동" aria-label="기록 표시 이동. 드래그 또는 방향키로 이동" aria-keyshortcuts="ArrowUp ArrowDown ArrowLeft ArrowRight"
 onKeyDown={e=>{const vectors:Record<string,[number,number]>={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]},v=vectors[e.key];if(!v)return;e.preventDefault();const r=panel.current!.getBoundingClientRect(),p=clamp({x:r.x+v[0],y:r.y+v[1]});setPosition(p);persist(p);}}
 onPointerDown={e=>{const r=panel.current!.getBoundingClientRect();drag.current={x:r.x,y:r.y,startX:e.clientX,startY:e.clientY};setDragging(true);e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerMove={e=>{const d=drag.current;if(d)setPosition(clamp({x:d.x+e.clientX-d.startX,y:d.y+e.clientY-d.startY}));}}
 onPointerUp={e=>{drag.current=null;setDragging(false);e.currentTarget.releasePointerCapture(e.pointerId);const r=panel.current!.getBoundingClientRect();persist(clamp({x:r.x,y:r.y}));}} onPointerCancel={()=>{drag.current=null;setDragging(false);}}><MiniIcon kind="grip"/></button><span className="record-mini-state">{stop?'종료 확인 중':paused?'잠시 멈춤':'기록 중'} <span className="record-mini-separator">·</span> {minutes}분</span><button className="record-mini-return" onClick={()=>onOpen(task.id)}>기록으로 <MiniIcon kind="arrow"/></button></div><div className="record-mini-main"><button className="record-mini-title" data-typo-role="title" title={task.title+' · 현재 기록으로'} onClick={()=>onOpen(task.id)}>{task.title}</button><div className="record-mini-controls"><button className="record-mini-control" disabled={locked||stop} aria-label={paused?'다시 시작':'잠시 멈춤'} onClick={()=>void send('switch_segment',{runId:run.id,kind:paused?'work':'pause',at:new Date().toISOString()})}><MiniIcon kind={paused?'play':'pause'}/></button><button className="record-mini-control" disabled={locked} aria-label="기록 종료" onClick={()=>{setStopAt(new Date().toISOString());setReason(run.blocked_reason);setStop(true);}}><MiniIcon kind="stop"/></button></div></div></aside>
 {stop&&<div className="modal-backdrop"><section className="stop-dialog" role="dialog" aria-modal="true" aria-labelledby="floating-stop-title"><div className="editor-head"><h2 id="floating-stop-title" data-typo-role="title">기록 종료</h2><button className="iconbtn" aria-label="닫기" onClick={()=>setStop(false)}>×</button></div><label className="field"><span>막힌 이유 · 선택</span><textarea data-typo-role="record-input" maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="form-help">종료해도 할 일의 완료 상태는 바뀌지 않습니다.</p><div className="form-actions"><button className="btn primary" disabled={locked} onClick={async()=>{if(await send('stop_run',{runId:run.id,at:stopAt,blockedReason:reason}))setStop(false);}}>기록 종료</button></div></section></div>}
 </>;
}
