'use client';
import {useState} from 'react';
import type {Reflection,Task,Thought} from '@/lib/contracts';
import {seoulDate} from '@/lib/schedule';
import {useJournal} from './journal-provider';
import {DateField} from './date-field';
import {BookmarkIcon} from './icons';
import {dateText} from './presentation';
export function Bookmark({active,onClick,disabled=false,filter=false}:{active:boolean;onClick:()=>void;disabled?:boolean;filter?:boolean}){return <button className={'btn sm bookmark-icon'+(filter?' library-bookmark-filter':'')} aria-label={filter?'책갈피에 표시한 회고만 보기':active?'책갈피 해제':'책갈피에 추가'} title={filter?'책갈피에 표시한 회고만 보기':active?'책갈피 해제':'책갈피에 추가'} aria-pressed={active} disabled={disabled} onClick={onClick}><BookmarkIcon active={active}/></button>;}
export function ThoughtEditor({task,day,readOnly=false}:{task:Task;day:string;readOnly?:boolean}){
 const {data,locked,send}=useJournal(),saved=data?.thoughts.find(t=>t.task_id===task.id&&t.local_date===day);const [editing,setEditing]=useState(false),[body,setBody]=useState(saved?.body||'');
 return <details className="day-thought"><summary data-typo-role="label">단상</summary><div className="thought-content">{readOnly?<p className="thought-body" data-typo-role="record">{saved?.body||'이 날짜에 남긴 단상이 없습니다.'}</p>:saved&&!editing?<><p className="thought-body" data-typo-role="record">{saved.body}</p><button className="btn sm" onClick={()=>{setBody(saved.body);setEditing(true);}}>수정</button></>:<form onSubmit={async e=>{e.preventDefault();if(await send('save_thought',{taskId:task.id,date:day,body}))setEditing(false);}}><label className="sr-only" htmlFor={'thought-'+task.id}>선택한 날의 단상</label><textarea id={'thought-'+task.id} data-typo-role="record-input" required rows={2} maxLength={4000} value={body} onChange={e=>setBody(e.target.value)} placeholder="이 일을 하며 떠오른 생각"/><div className="actions"><button className="btn sm" disabled={locked} type="submit">저장</button>{editing&&<button type="button" className="btn sm" onClick={()=>setEditing(false)}>취소</button>}</div></form>}</div></details>;
}
export function ReflectionEditor({day,saved,onSaved,onCancel,closing=false}:{day:string;saved?:Reflection;onSaved:()=>void;onCancel?:()=>void;closing?:boolean}){
 const {data,locked,send}=useJournal();const [body,setBody]=useState(saved?.body||''),[imports,setImports]=useState<{id:string;body:string}[]>(saved?.imported_thoughts||[]),[error,setError]=useState('');const available=data?.thoughts.filter(t=>t.local_date===day&&!imports.some(i=>i.id===t.id))||[];
 function add(t:Thought){if(body.length+t.body.length+(body?2:0)>4000){setError('회고는 4,000자 이내로 작성해 주세요.');return;}setBody(body?body+'\n\n'+t.body:t.body);setImports([...imports,{id:t.id,body:t.body}]);}
 return <section className="review-note-editor" tabIndex={-1}><div className="row spread"><h2 data-typo-role="title">{saved?'회고 수정':'오늘의 회고 쓰기'}</h2>{onCancel&&<button className="iconbtn" type="button" aria-label="회고 작성 닫기" onClick={onCancel}>×</button>}</div><p className="small muted">{dateText(day,true)}</p><form onSubmit={async e=>{e.preventDefault();setError('');if(closing&&data?.runs.some(r=>!r.ended_at)){setError('진행 중인 기록을 먼저 마쳐 주세요.');return;}if(await send(closing?'close_day':'save_reflection',{date:day,body,imports}))onSaved();}}><label className="field"><span>오늘은 어떤 하루였나요?</span><textarea data-typo-role="record-input" required={!closing||!!saved} maxLength={4000} value={body} onChange={e=>setBody(e.target.value)} placeholder={closing?'기억하고 싶은 순간이나 생각을 자유롭게 적어 보세요. 회고를 작성하지 않아도 마무리할 수 있습니다.':'기억하고 싶은 순간이나 생각을 자유롭게 적어 보세요.'}/></label><details className="diary-source-notes"><summary data-typo-role="label">이 날짜의 단상 가져오기</summary>{available.map(t=><article key={t.id}><strong data-typo-role="title">{[...(data?.tasks||[]),...(data?.retainedTasks||[])].find(v=>v.id===t.task_id)?.title||'지난 할 일'}</strong><p data-typo-role="record">{t.body}</p><button className="btn sm" type="button" disabled={body.length+t.body.length+(body?2:0)>4000} onClick={()=>add(t)}>가져오기</button></article>)}{!available.length&&<p className="small muted">가져올 새 단상이 없습니다.</p>}</details>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions">{onCancel&&<button className="btn" type="button" onClick={onCancel}>취소</button>}<button className="btn primary" disabled={locked} type="submit">{closing?'마무리하기':'회고 저장'}</button></div></form></section>;
}
export function DayClosing({day,onArchive=()=>{},onCurrent=()=>{}}:{day:string;onArchive?:()=>void;onCurrent?:(id:string)=>void}){
 const {data}=useJournal();const [stage,setStage]=useState<'closed'|'idle'|'tasks'|'write'>('idle'),saved=data?.reflections.find(r=>r.local_date===day),closed=stage==='closed'||data?.closures.some(c=>c.local_date===day),current=data?.runs.find(r=>!r.ended_at),today=seoulDate();const unfinished=data?.tasks.filter(t=>!t.complete&&!t.skipped&&!t.cancelled_at&&t.due_date===day)||[];
 if(stage==='write')return <ReflectionEditor key={saved?.id||day} day={day} saved={saved} closing onSaved={()=>setStage('closed')} onCancel={()=>setStage('idle')}/>;
 if(stage==='tasks')return <section className="review-note-editor day-close-card" tabIndex={-1}><div className="row spread"><p className="reflection-text" data-typo-role="label">{day===today?'오늘':'선택한 날'} 마감인 미완료 할 일 {unfinished.length}개</p><button className="iconbtn" aria-label="하루 마무리 닫기" onClick={()=>setStage('idle')}>×</button></div><p className="small muted">마무리해도 할 일이 자동 완료되거나 기록이 잠기지 않습니다.</p>{current?<><p className="alert">{data?.tasks.find(t=>t.id===current.task_id)?.title||'할 일'}의 실행 기록이 열려 있습니다. 기록을 먼저 마쳐 주세요.</p><div className="actions close-next"><button className="btn primary" onClick={()=>onCurrent(current.task_id)}>현재 기록 확인</button></div></>:<div className="actions close-next"><button className="btn primary" onClick={()=>setStage('write')}>회고 작성</button></div>}</section>;
 return <div className="end-day"><div><h3 data-typo-role="title">{closed?'하루를 마무리했습니다.':day===today?'오늘 마무리':'하루 마무리'}</h3><p className="small muted">{closed?'시간 기록과 회고는 나중에도 수정할 수 있습니다.':'단상을 확인하고 회고를 작성할 수 있습니다.'}</p></div>{day<=today&&(closed&&saved?<button className="btn sm" onClick={onArchive}>저장한 회고 보기</button>:<button className="btn sm" disabled={!data} onClick={()=>setStage('tasks')}>{closed?'회고 작성':day===today?'오늘 마무리':'하루 마무리'}</button>)}</div>;
}
function ReflectionCard({value,onDay}:{value:Reflection;onDay:(day:string)=>void}){
 const {locked,send}=useJournal();const [editing,setEditing]=useState(false);
 return <article className={'reflection-card diary-card'+(editing?' inline-reflection':'')} tabIndex={-1} id={'reflection-'+value.id}>{editing?<ReflectionEditor day={value.local_date} saved={value} onSaved={()=>setEditing(false)} onCancel={()=>setEditing(false)}/>:<><header><div><span className="eyebrow">회고</span><h3 data-typo-role="title">{dateText(value.local_date,true)}</h3></div><details className="diary-menu"><summary aria-label="회고 수정 및 삭제">⋯</summary><div className="actions"><button className="btn sm" onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');setEditing(true);}}>수정</button><button className="btn sm" disabled={locked} onClick={()=>{if(window.confirm('이 회고를 휴지통으로 옮길까요?'))void send('delete_entity',{entityType:'reflection',entityId:value.id,at:new Date().toISOString()});}}>삭제</button></div></details></header><button className="reflection-day-link reflection-text" data-typo-role="record" aria-label={dateText(value.local_date,true)+' 일간 보기'} onClick={()=>onDay(value.local_date)}>{value.body}</button><footer><button className="btn sm reflection-date-link" onClick={()=>onDay(value.local_date)}>일간 보기</button><Bookmark active={value.bookmarked} disabled={locked} onClick={()=>void send('bookmark_reflection',{reflectionId:value.id,bookmarked:!value.bookmarked})}/></footer></>}</article>;
}
export function Archive({onDay}:{onDay:(day:string,taskId?:string)=>void}){
 const {data,locked,send}=useJournal();const [tab,setTab]=useState<'reflections'|'trash'>('reflections'),[bookmarks,setBookmarks]=useState(false),[date,setDate]=useState(''),[query,setQuery]=useState(''),[restoreOverlap,setRestoreOverlap]=useState<Record<string,boolean>>({});const lower=query.toLocaleLowerCase('ko'),reflections=data?.reflections.filter(r=>(!bookmarks||r.bookmarked)&&(!date||r.local_date===date)&&(!query||(r.body+' '+r.local_date+' '+dateText(r.local_date,true)).toLocaleLowerCase('ko').includes(lower)))||[];
 return <div className="content-surface"><div className="page-head"><div><span className="eyebrow">MY ARCHIVE</span><h1 data-typo-role="title">보관함</h1></div></div><div className="review-tabs" aria-label="보관함 분류"><button data-typo-role="menu" aria-pressed={tab==='reflections'} onClick={()=>setTab('reflections')}>회고 모음</button><button data-typo-role="menu" aria-pressed={tab==='trash'} onClick={()=>setTab('trash')}>휴지통</button></div><section id="journal-library-content" tabIndex={-1}>
 {tab==='reflections'&&<><div className="library-filters"><div className="library-date-filter"><DateField label="날짜" value={date} onChange={setDate}/></div><label className="library-search-filter">검색<input type="search" placeholder="내용 또는 날짜" value={query} onChange={e=>setQuery(e.target.value)}/></label><Bookmark active={bookmarks} filter onClick={()=>setBookmarks(!bookmarks)}/></div>{reflections.map(r=><ReflectionCard key={r.id} value={r} onDay={onDay}/>)}{!reflections.length&&<p className="empty">{data?'조건에 맞는 회고가 없습니다.':'저장소 연결 후 회고를 확인할 수 있습니다.'}</p>}</>}
 {tab==='trash'&&<><p className="trash-record-note">삭제한 계획·할 일·예정 배치·실행 기록·회고를 복원할 수 있습니다. 계획과 할 일을 삭제해도 실제 기록·단상·회고는 보존됩니다. 영구 삭제는 제공하지 않습니다.</p>{data?.trash.map(t=>{const run=data.runs.find(r=>t.entity_type==='task'?r.task_id===t.entity_id:t.entity_type==='plan'?data.retainedTasks?.some(k=>k.id===r.task_id&&k.plan_id===t.entity_id):r.id===t.entity_id);return <article className="trash-item" key={t.id}><div className="trash-title"><h3 data-typo-role="title">{t.title}</h3><button className="btn sm" disabled={locked||!!t.placement_conflict&&!restoreOverlap[t.id]} onClick={()=>void send('restore_entity',{trashId:t.id,allowOverlap:!!restoreOverlap[t.id]})}>복원</button></div><p>{({plan:'계획',task:'할 일',run:'실행 기록',placement:'계획 배치',reflection:'회고',routine:'반복 예외'})[t.entity_type]} · {dateText(seoulDate(new Date(t.deleted_at)))} 삭제</p>{t.placement_conflict&&<label className="detail-complete"><input type="checkbox" checked={!!restoreOverlap[t.id]} onChange={e=>setRestoreOverlap(v=>({...v,[t.id]:e.target.checked}))}/>예정 시간 겹침을 확인했으며 그대로 복원</label>}{run&&<button className="btn sm" onClick={()=>onDay(seoulDate(new Date(run.started_at)),run.task_id)}>보존한 기록 보기</button>}</article>;})}{!data?.trash.length&&<div className="empty"><p>휴지통이 비어 있습니다.</p></div>}</>}
 </section></div>;
}
