'use client';
import {useState} from 'react';
import {useJournal} from './journal-provider';
import {duration,planResults,usageForDay,type Metric} from '@/lib/review';
import {addDays,clockLabel,seoulDate,weekDays} from '@/lib/schedule';
import {DateField} from './date-field';
const labels:Record<Metric,string>={planned:'계획한 할 일',complete:'완료',delayed:'지연',blocked:'막힘',expected:'예상 시간',actual:'실제 작업',difference:'실제 − 예상'};
export function Review({now,onDay}:{now:number;onDay:(day:string,taskId?:string)=>void}){
 const {data,locked,send}=useJournal();const [tab,setTab]=useState<'results'|'usage'>('results'),[planId,setPlanId]=useState('all'),[period,setPeriod]=useState<'all'|'week'>('all'),[metric,setMetric]=useState<Metric|null>(null),[week,setWeek]=useState(seoulDate()),[usageDay,setUsageDay]=useState('');
 const [improvement,setImprovement]=useState(''),[target,setTarget]=useState(''),[newTitle,setNewTitle]=useState(''),[start,setStart]=useState(seoulDate()),[end,setEnd]=useState(addDays(seoulDate(),30));
 const result=data?planResults(data,planId,period,seoulDate(now)):null,days=weekDays(week),usage=data?days.map(d=>usageForDay(data,d)):[];
 const totals=usage.reduce((a,v)=>({work:a.work+v.totals.work,break:a.break+v.totals.break,interrupt:a.interrupt+v.totals.interrupt}),{work:0,break:0,interrupt:0});
 return <><div className="page-title"><div><small>SEE</small><h2>돌아보기</h2></div></div><nav className="view-tabs" aria-label="돌아보기 메뉴"><button aria-pressed={tab==='results'} onClick={()=>setTab('results')}>계획 결과</button><button aria-pressed={tab==='usage'} onClick={()=>setTab('usage')}>날짜별 시간 사용</button></nav>
 {!data&&<p className="empty">저장소 연결 후 기록을 돌아볼 수 있습니다.</p>}
 {data&&tab==='results'&&<><h3>계획한 일을 얼마나 진행했나?</h3><p className="field-help">일반 계획의 할 일을 집계합니다. 루틴의 실제 활동은 날짜별 시간 사용에서 확인합니다.</p><div className="review-scope"><label>대상 계획<select value={planId} onChange={e=>setPlanId(e.target.value)}><option value="all">모든 일반 계획</option>{data.plans.filter(p=>p.kind==='general').map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>할 일 마감일 범위<select value={period} onChange={e=>setPeriod(e.target.value as 'all'|'week')}><option value="all">전체 기간</option><option value="week">이번 주 마감</option></select></label></div>
 <div className="metrics">{(Object.keys(labels) as Metric[]).map(id=><button key={id} aria-pressed={metric===id} onClick={()=>setMetric(metric===id?null:id)}><span>{labels[id]}</span><strong>{['expected','actual','difference'].includes(id)?duration(result!.values[id]):result!.values[id]}</strong><svg className="pen-line" viewBox="0 0 180 8" preserveAspectRatio="none" aria-hidden="true"><path d="M3 5 Q40 1 84 4 T176 3" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/><path d="M10 7 Q89 5 161 6" fill="none" stroke="currentColor" strokeWidth=".8" strokeLinecap="round"/></svg></button>)}</div><p className="field-help">숫자를 선택하면 근거가 아래에 펼쳐집니다. 완료·지연은 현재 상태, 막힘·실제 시간은 대상 할 일의 종료 기록 기준입니다.</p>
 {metric&&<section className="evidence"><h3>{labels[metric]}의 근거</h3>{result!.evidence[metric].map(t=><details key={t.id}><summary className="evidence-heading"><span><strong className="task-title">{t.title}</strong><span className="field-help">{t.complete?'완료':'미완료'} · 예상 {t.estimated_minutes}분 · 실제 {duration(result!.runs.filter(r=>r.task_id===t.id).reduce((n,r)=>n+Number(r.work_seconds)*1000,0))}</span></span><span className="evidence-chevron" aria-hidden="true">›</span></summary>{result!.runs.filter(r=>r.task_id===t.id).map(r=><article className="run-row" key={r.id}><p>{seoulDate(new Date(r.started_at))} · {clockLabel(r.started_at)}–{clockLabel(r.ended_at!)} · 작업 {duration(Number(r.work_seconds)*1000)}</p>{r.blocked_reason&&<p className="record-body">{r.blocked_reason}</p>}<button className="text-button" onClick={()=>onDay(seoulDate(new Date(r.started_at)),t.id)}>일간 상세 →</button></article>)}{!result!.runs.some(r=>r.task_id===t.id)&&<p className="field-help">종료한 실행 기록이 없습니다.</p>}</details>)}{!result!.evidence[metric].length&&<p className="empty">해당하는 할 일이 없습니다.</p>}</section>}
 {planId!=='all'&&<section><h3>다음 계획으로</h3><form onSubmit={async e=>{e.preventDefault();const saved=await send(target==='new'?'create_plan':'send_improvement',target==='new'?{kind:'general',title:newTitle,startDate:start,endDate:end,sourcePlanId:planId,improvementText:improvement}:{sourcePlanId:planId,targetPlanId:target,body:improvement});if(saved){setImprovement('');setTarget('');setNewTitle('');}}}><fieldset disabled={locked}><label>고칠 점 한 가지<textarea required maxLength={500} value={improvement} onChange={e=>setImprovement(e.target.value)}/></label><label>다음 계획<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">선택하세요</option>{data.plans.filter(p=>p.kind==='general'&&p.id!==planId).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}<option value="new">새 계획 만들기</option></select></label>{target==='new'&&<><label>계획 제목<input required maxLength={120} value={newTitle} onChange={e=>setNewTitle(e.target.value)}/></label><div className="form-grid"><DateField label="시작일" required value={start} onChange={setStart}/><DateField label="종료일" required value={end} onChange={setEnd}/></div></>}<div className="actions"><button type="submit">개선점 전달</button></div></fieldset></form></section>}
 </>}
 {data&&tab==='usage'&&<><h3>그날 시간을 어떻게 썼나?</h3><p className="field-help">한 주의 시간을 돌아봅니다. 마감일과 관계없이 실제 활동한 날짜에 나누며 진행 중인 기록은 합계에서 제외합니다.</p><div className="usage-week"><button className="text-button" onClick={()=>setWeek(addDays(week,-7))} aria-label="이전 주">‹</button><strong className="date-range">{days[0].slice(5).replace('-','.')}–{days[6].slice(5).replace('-','.')}</strong><button className="text-button" onClick={()=>setWeek(addDays(week,7))} aria-label="다음 주">›</button><button onClick={()=>setWeek(seoulDate(now))}>이번 주</button></div><div className="usage-totals">{(['work','break','interrupt'] as const).map(key=><div key={key}><span>{key==='work'?'작업':key==='break'?'휴식':'중단'}</span><strong>{duration(totals[key])}</strong></div>)}</div>
 <div className="usage-chart">{usage.map(v=>{const total=v.totals.work+v.totals.break+v.totals.interrupt,max=Math.max(3600000,...usage.map(x=>x.totals.work+x.totals.break+x.totals.interrupt));return <button key={v.day} className="usage-column" aria-pressed={usageDay===v.day} onClick={()=>setUsageDay(usageDay===v.day?'':v.day)}><span className="usage-stack" style={{height:Math.max(2,total/max*160)}}>{(['interrupt','break','work'] as const).map(key=><span className={key} key={key} style={{height:total?v.totals[key]/total*100+'%':'0'}}/>)}</span><span>{Number(v.day.slice(8))}일</span><small>{duration(total)}</small></button>;})}</div><p className="field-help">날짜를 선택하면 작업·휴식·중단 시간과 근거 기록을 확인할 수 있습니다.</p>
 {usageDay&&<section><h3>{usageDay}의 시간</h3>{usage.find(v=>v.day===usageDay)?.rows.map(({run:r,parts})=><article key={r.id} className="run-row"><h4 className="task-title">{data.tasks.find(t=>t.id===r.task_id)?.title||r.task_title}</h4><p>작업 {duration(parts.work)} · 휴식 {duration(parts.break)} · 중단 {duration(parts.interrupt)}</p><button className="text-button" onClick={()=>onDay(usageDay,r.task_id)}>일간 상세 →</button></article>)}{!usage.find(v=>v.day===usageDay)?.rows.length&&<p className="empty">종료한 실행 기록이 없습니다.</p>}</section>}
 </>}
 </>;
}
