'use client';
import {InkUnderline} from './ink-underline';
import {useEffect,useRef,useState} from 'react';
import {useJournal} from './journal-provider';
import {duration,planResults,usageForDay,type Metric} from '@/lib/review';
import {addDays,clockLabel,dayWindow,seoulDate,weekDays} from '@/lib/schedule';
import {DateField} from './date-field';
import {PriorityField,DurationField} from './forms';
import type {Priority} from '@/lib/contracts';
import {ChevronIcon} from './icons';
import {dateText} from './presentation';
const labels:Record<Metric,string>={planned:'계획한 할 일',complete:'완료',delayed:'지연',blocked:'막힘',expected:'예상 시간',actual:'실제 작업',difference:'실제 − 예상'};
const counts:Metric[]=['planned','complete','delayed','blocked'],times:Metric[]=['expected','actual','difference'];
export function Review({now,onDay,onPlan=()=>{}}:{now:number;onDay:(day:string,taskId?:string)=>void;onPlan?:(id?:string)=>void}){
 const {data,locked,send}=useJournal();const [tab,setTab]=useState<'results'|'usage'>('results'),[planId,setPlanId]=useState('all'),[period,setPeriod]=useState<'all'|'week'>('all'),[metric,setMetric]=useState<Metric|null>(null),[week,setWeek]=useState(seoulDate()),[usageDay,setUsageDay]=useState('');
 const [improvement,setImprovement]=useState(''),[target,setTarget]=useState(''),[creating,setCreating]=useState(false),[newTitle,setNewTitle]=useState(''),[start,setStart]=useState(addDays(seoulDate(),1)),[end,setEnd]=useState(addDays(seoulDate(),31)),[success,setSuccess]=useState(''),[estimate,setEstimate]=useState(0),[priority,setPriority]=useState<Priority>('normal'),[receipt,setReceipt]=useState(''),[receiptPlan,setReceiptPlan]=useState('');
 const improvementDrafts=useRef<Record<string,string>>({});
 const evidence=useRef<HTMLElement>(null),result=data?planResults(data,planId,period,seoulDate(now)):null,days=weekDays(week),usage=data?days.map(d=>usageForDay(data,d)):[];
 const totals=usage.reduce((a,v)=>({work:a.work+v.totals.work,break:a.break+v.totals.break,interrupt:a.interrupt+v.totals.interrupt}),{work:0,break:0,interrupt:0}),selected=usage.find(v=>v.day===usageDay)||usage.find(v=>v.day===seoulDate(now))||usage.find(v=>v.rows.length)||usage[0];
 useEffect(()=>{if(metric)evidence.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});},[metric]);
 async function apply(create=false){if(target==='new'&&!create){setCreating(true);return;}const saved=await send(create?'create_plan':'send_improvement',create?{kind:'general',title:newTitle,startDate:start,endDate:end,successText:success,estimatedMinutes:estimate,priority,sourcePlanId:planId,improvementText:improvement}:{sourcePlanId:planId,targetPlanId:target,body:improvement});if(saved){setReceiptPlan(create?saved.entityId||'':target);setReceipt('개선점을 다음 계획에 반영했습니다.');setCreating(false);improvementDrafts.current[planId]='';setImprovement('');setTarget('');}}
 function metrics(ids:Metric[],time=false){return <div className={'metrics'+(time?' time-metrics':'')}>{ids.map(id=><button className="metric" key={id} aria-pressed={metric===id} onClick={()=>setMetric(metric===id?null:id)}><span data-typo-role="label">{labels[id]}</span><strong data-typo-role="number">{time?duration(result!.values[id]):result!.values[id]}{metric===id&&<InkUnderline/>}</strong></button>)}</div>;}
 return <div className="review-surface"><div className="page-head"><div><div className="eyebrow">SEE / 돌아보기</div><h1 data-typo-role="title">돌아보기</h1></div></div><div className="review-tabs" aria-label="돌아보기 구역"><button data-typo-role="menu" aria-pressed={tab==='results'} onClick={()=>setTab('results')}>계획 결과</button><button data-typo-role="menu" aria-pressed={tab==='usage'} onClick={()=>setTab('usage')}>날짜별 시간 사용</button></div>
 {!data&&<p className="empty">저장소 연결 후 기록을 돌아볼 수 있습니다.</p>}
 {data&&tab==='results'&&<><div className="scope-row" style={{margin:'0 0 20px'}}><label>대상 일반 계획<select value={planId} onChange={e=>{improvementDrafts.current[planId]=improvement;setImprovement(improvementDrafts.current[e.target.value]||'');setTarget('');setCreating(false);setPlanId(e.target.value);setMetric(null);setReceipt('');}}><option value="all">모든 일반 계획</option>{data.plans.filter(p=>p.kind==='general').map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div><h2 data-typo-role="title">계획한 일을 얼마나 진행했나?</h2><p className="review-scope-note">일반 계획의 할 일을 집계합니다. 루틴의 실제 활동은 날짜별 시간 사용에서 확인할 수 있습니다.</p><div className="scope-row"><label>할 일 마감일 범위<select value={period} onChange={e=>{setPeriod(e.target.value as 'all'|'week');setMetric(null);}}><option value="all">전체 기간</option><option value="week">이번 주 마감</option></select></label></div>
 {metrics(counts)}{metrics(times,true)}<p className="small muted" style={{marginTop:12}}>숫자를 선택하면 근거가 아래에 펼쳐집니다. 완료·지연은 현재 상태, 실제 시간은 대상 할 일의 종료 기록 기준입니다.</p>
 {metric&&<section ref={evidence} className="evidence" tabIndex={-1}><div className="row spread"><h3 data-typo-role="title">{labels[metric]}의 근거</h3><button className="btn sm" onClick={()=>setMetric(null)}>닫기</button></div>{metric==='blocked'&&<p className="small muted">막힌 이유가 저장된 할 일을 한 번씩 셉니다. 완료한 일도 포함할 수 있습니다.</p>}<div className="evidence-list">{result!.evidence[metric].map(t=>{const runs=result!.runs.filter(r=>r.task_id===t.id&&(metric!=='blocked'||r.blocked_reason.trim()));return <details className="evidence-item" key={t.id}><summary className="evidence-summary"><span className="evidence-heading"><strong className="evidence-title" data-typo-role="title">{t.title}</strong><span className="evidence-meta">{t.complete?'완료':'미완료'} · {metric==='blocked'?'이유가 있는 실행 '+runs.length+'건':'예상 '+duration(t.estimated_minutes*60000)+' · 실제 '+duration(runs.reduce((n,r)=>n+Number(r.work_seconds)*1000,0))}</span></span><span className="evidence-indicator"><ChevronIcon/></span></summary><div className="evidence-detail">{t.description&&<p className="evidence-description" data-typo-role="record">{t.description}</p>}{t.due_date&&<p className="evidence-date">마감 {dateText(t.due_date)}</p>}{runs.map(r=><article className="evidence-run" key={r.id}><strong className="evidence-run-time">{dateText(seoulDate(new Date(r.started_at)))} {clockLabel(r.started_at)}–{clockLabel(r.ended_at!)}</strong><div className="evidence-run-facts"><span>작업 {duration(Number(r.work_seconds)*1000)}</span><span>멈춤 {duration(r.segments.filter(s=>s.kind!=='work').reduce((n,s)=>n+Date.parse(s.ended_at!)-Date.parse(s.started_at),0))}</span><span>{r.source==='live'?'타이머 기록':'수기 기록'}</span></div>{r.blocked_reason&&<p className="blocked-reason-text" data-typo-role="record"><span data-typo-role="info">막힌 이유</span>{r.blocked_reason}</p>}<details className="evidence-segments"><summary>작업·멈춤 구간</summary><ul>{r.segments.map(s=><li key={s.id}>{s.kind==='work'?'작업':s.kind==='break'?'휴식':'중단'} · {dateText(seoulDate(new Date(s.started_at)))} {clockLabel(s.started_at)}–{clockLabel(s.ended_at!)} · {duration(Date.parse(s.ended_at!)-Date.parse(s.started_at))}</li>)}</ul></details><button className="link" onClick={()=>onDay(seoulDate(new Date(r.started_at)),t.id)}>일간 상세 →</button></article>)}{!runs.length&&<><p className="small muted">종료한 실행 기록이 없습니다.</p><button className="link" onClick={()=>onDay(t.due_date||seoulDate(now),t.id)}>일간 상세 →</button></>}</div></details>;})}{!result!.evidence[metric].length&&<p className="review-intro">해당하는 할 일이 없습니다.</p>}</div></section>}
 {planId==='all'?<p className="small muted" style={{marginTop:24}}>계획을 선택하면 다음 계획에서 바꿀 점을 남길 수 있습니다.</p>:<details className="improvement-composer"><summary data-typo-role="label">다음 계획에서 바꿀 점</summary><div className="improvement-body"><label className="field"><span>다음 계획에서 바꿀 점</span><input type="text" data-typo-role="record-input" maxLength={500} value={improvement} onChange={e=>setImprovement(e.target.value)} placeholder="다음에는 무엇을 다르게 해볼까요?"/></label><label className="field improvement-target"><span>반영할 다음 계획</span><select value={target} onChange={e=>{setTarget(e.target.value);setCreating(false);}}><option value="">계획 선택</option>{data.plans.filter(p=>p.kind==='general'&&p.id!==planId).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}<option value="new">새 계획 만들기</option></select></label>{creating?<section className="improvement-inline-plan"><h3 data-typo-role="title">다음 계획 만들기</h3><form onSubmit={e=>{e.preventDefault();void apply(true);}}><fieldset disabled={locked}><div className="formgrid"><label className="field wide"><span>계획 제목</span><input required maxLength={120} value={newTitle} onChange={e=>setNewTitle(e.target.value)}/></label><DateField label="시작일" required value={start} onChange={setStart}/><DateField label="종료일" required min={start} value={end} onChange={setEnd}/><label className="field wide"><span>성공 기준</span><textarea required data-typo-role="record-input" maxLength={4000} value={success} onChange={e=>setSuccess(e.target.value)}/></label><DurationField label="계획 전체 예상 시간" max={525600} value={estimate} onChange={setEstimate}/><PriorityField value={priority} onChange={setPriority}/></div><p className="small muted">개선점도 이 계획과 함께 저장됩니다.</p><div className="actions"><button className="btn" type="button" onClick={()=>setCreating(false)}>취소</button><button className="btn primary">계획과 개선점 저장</button></div></fieldset></form></section>:<button className="btn primary" disabled={locked||!improvement.trim()||!target} onClick={()=>void apply()}>{target==='new'?'다음 계획 만들기':'다음 계획에 반영'}</button>}{receipt&&<p className="improvement-receipt" role="status">{receipt} <button className="btn sm" onClick={()=>onPlan(receiptPlan)}>반영한 계획 보기</button></p>}</div></details>}
 </>}
 {data&&tab==='usage'&&<><h2 data-typo-role="title">한 주의 시간을 돌아봅니다.</h2><p className="review-intro">종료한 실행 기록의 작업·휴식·중단 시간을 비교합니다. 날짜를 누르면 그날의 기록을 확인할 수 있습니다. 진행 중 기록은 합계에서 제외합니다.</p><div className="review-week-range"><strong data-typo-role="title">{days[0].slice(5).replace('-','.')}–{days[6].slice(5).replace('-','.')}</strong><div className="review-week-controls"><button className="btn sm" onClick={()=>setWeek(addDays(week,-7))}>‹ 이전 주</button><button className="btn sm" onClick={()=>setWeek(seoulDate(now))}>이번 주</button><button className="btn sm" onClick={()=>setWeek(addDays(week,7))}>다음 주 ›</button></div></div><UsageTotals value={totals}/>
 <section className="time-chart" aria-label="요일별 시간 사용"><div className="time-chart-legend">{(['work','break','interrupt'] as const).map(k=><span className="time-chart-key" key={k}><i className={'time-chart-swatch time-part-'+k}/>{k==='work'?'작업':k==='break'?'휴식':'중단'}</span>)}</div><div className="time-chart-grid">{usage.map((v,i)=>{const total=v.totals.work+v.totals.break+v.totals.interrupt,max=Math.max(1,...usage.map(x=>x.totals.work+x.totals.break+x.totals.interrupt));return <button className="time-chart-day" key={v.day} aria-pressed={selected?.day===v.day} aria-label={dateText(v.day,true)+' · '+duration(total)} onClick={()=>setUsageDay(v.day)}><span className="time-chart-total">{total?duration(total):'기록 없음'}</span><span className="time-chart-track" aria-hidden="true">{(['interrupt','break','work'] as const).map(k=><span className={'time-chart-segment time-part-'+k} key={k} style={{height:v.totals[k]/max*100+'%'}}/>)}</span><span className="time-chart-date" data-typo-role="number">{'일월화수목금토'[i]}<small>{Number(v.day.slice(5,7))}.{Number(v.day.slice(8))}</small></span></button>;})}</div></section>
 {selected&&<section className="time-chart-detail"><h3 data-typo-role="title">{dateText(selected.day,true)}의 기록</h3><UsageTotals value={selected.totals}/>{selected.rows.map(({run:r,parts})=>{const {from,to}=dayWindow(selected.day);return <div className="record-row" key={r.id}><div className="record-row-head"><div><strong data-typo-role="title">{[...data.tasks,...(data.retainedTasks||[])].find(t=>t.id===r.task_id)?.title||r.task_title||'지난 할 일'}</strong><small>{clockLabel(Math.max(from,Date.parse(r.started_at)))}–{Date.parse(r.ended_at!)>=to?'다음 날 00:00':clockLabel(r.ended_at!)} · 작업 {duration(parts.work)}</small><small>휴식 {duration(parts.break)} · 중단 {duration(parts.interrupt)}</small></div><button className="btn sm" onClick={()=>onDay(selected.day,r.task_id)}>일간 상세</button></div></div>;})}{!selected.rows.length&&<p className="small muted">종료한 실행 기록이 없습니다.</p>}</section>}<p className="small muted">삭제한 할 일의 실제 실행 기록도 포함합니다.</p>
 </>}
 </div>;
}
function UsageTotals({value}:{value:{work:number;break:number;interrupt:number}}){return <div className="usage-totals">{(['work','break','interrupt'] as const).map(k=><div key={k}><span>{k==='work'?'작업':k==='break'?'휴식':'중단'}</span><strong data-typo-role="number">{duration(value[k])}</strong></div>)}</div>;}
