'use client';
import {useEffect,useRef,useState} from 'react';
import type {Run,Snapshot,Task} from '@/lib/contracts';
import {addDays,clockLabel,dayItems,dayWindow,overlaps,runWork,seoulDate,weekDays} from '@/lib/schedule';
import {duration} from '@/lib/review';
import {useJournal} from './journal-provider';
import {DateField} from './date-field';
import {RunEditor} from './run-editor';
import {TaskEditor} from './plans';
import {RoutineEditor} from './routines';
import {ThoughtEditor,DayClosing} from './records';
import {ListIcon} from './icons';
import {Timeline,type TimelineSelection} from './timeline';
import {Monthly} from './monthly';
import {dateButtonText,dateText,priorityText} from './presentation';
const weekdays=['일','월','화','수','목','금','토'];
const allTasks=(data:Snapshot)=>[...data.tasks,...(data.retainedTasks||[])];
function monthShift(day:string,delta:number){const [y,m,d]=day.split('-').map(Number),last=new Date(Date.UTC(y,m+delta,0)).getUTCDate();return new Date(Date.UTC(y,m-1+delta,Math.min(d,last))).toISOString().slice(0,10);}
type Editor={task:Task;mode:'placement'|'run';runId?:string;placementId?:string;startAt?:string};
export function Schedule({day,setDay,selectedId,setSelectedId,now,openRequest,onPlan,onArchive,onViewChange}:{day:string;setDay:(v:string)=>void;selectedId:string;setSelectedId:(v:string)=>void;now:number;openRequest:number;onPlan:()=>void;onArchive:()=>void;onEditTask?:(id:string)=>void;onViewChange?:(view:string)=>void}){
 const {data,locked,blocked,send}=useJournal();const [view,setView]=useState<'daily'|'weekly'|'monthly'>('daily'),[listCollapsed,setListCollapsed]=useState(false),[mobileOpen,setMobileOpen]=useState(true),[query,setQuery]=useState(''),[expanded,setExpanded]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[taskEditing,setTaskEditing]=useState<Task|null>(null),[routineEditing,setRoutineEditing]=useState<Task|null>(null),[early,setEarly]=useState(false),[stop,setStop]=useState<Run|null>(null),[reason,setReason]=useState(''),[stopAt,setStopAt]=useState('');
 const [selection,setSelection]=useState<TimelineSelection|null>(null),[focusRequest,setFocusRequest]=useState(0),[placementOpen,setPlacementOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false);
 const detail=useRef<HTMLElement>(null),actualStart=useRef<HTMLDivElement>(null),planned=useRef<HTMLDetailsElement>(null),editorPanel=useRef<HTMLDivElement>(null),today=seoulDate(now),days=weekDays(day),selected=data&&allTasks(data).find(t=>t.id===selectedId),live=data?.runs.find(r=>!r.ended_at),retained=!!data?.retainedTasks?.some(t=>t.id===selectedId),future=day>today;
 useEffect(()=>{onViewChange?.(view);},[view,onViewChange]);
 useEffect(()=>{if(live&&day===today&&!selectedId)setSelectedId(live.task_id);},[live?.id,day,today,selectedId,setSelectedId]);
 useEffect(()=>{if(openRequest){setView('daily');setEditor(null);setTaskEditing(null);setMobileOpen(false);}},[openRequest]);
 useEffect(()=>{if(!selectedId||view!=='daily')return;const frame=requestAnimationFrame(()=>{const target=selection?.kind==='placement'?planned.current:live?.task_id===selectedId?actualStart.current:detail.current;detail.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});(target||detail.current)?.focus({preventScroll:true});});return()=>cancelAnimationFrame(frame);},[selectedId,day,openRequest,focusRequest,view]);
 useEffect(()=>{if(editor&&!editor.startAt)editorPanel.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[editor]);
 useEffect(()=>{setSelection(null);setPlacementOpen(false);setHistoryOpen(false);},[day,openRequest]);
 function choose(id:string){setSelectedId(id);setMobileOpen(false);setEditor(null);setTaskEditing(null);setSelection(null);setPlacementOpen(false);setHistoryOpen(false);setFocusRequest(n=>n+1);}
 function chooseTimeline(value:TimelineSelection){choose(value.taskId);setSelection(value);setPlacementOpen(value.kind==='placement');setHistoryOpen(value.kind==='run');}
 function openDay(d:string,id=''){setView('daily');setDay(d);choose(id);}
 function shift(delta:number){setDay(view==='monthly'?monthShift(day,delta):addDays(day,delta*(view==='weekly'?7:1)));setSelectedId('');setEditor(null);}
 const listed=(data?.tasks.filter(t=>!t.cancelled_at&&(!t.routine_id||t.occurrence_date===day))||[]),eligible=listed.filter(t=>!t.skipped),search=query.trim().toLocaleLowerCase('ko');
 function listBody(mobile=false){return <><label className="day-list-search"><span className="sr-only">할 일 또는 계획 검색</span><input type="search" placeholder="할 일 찾기" value={query} onChange={e=>setQuery(e.target.value)}/></label>
  <div>{data?.plans.map((p,i)=>{const rows=listed.filter(t=>t.plan_id===p.id&&(!search||(t.title+' '+t.description+' '+p.title).toLocaleLowerCase('ko').includes(search)));if(!rows.length)return null;const count=rows.filter(t=>!t.skipped);return <details className="day-plan" key={p.id} open={!!search||selected?.plan_id===p.id||!selectedId&&i===0}><summary><span className="day-plan-name" data-typo-role="title">{p.title}{p.kind==='routine'&&<span className="routine-badge" data-typo-role="info">↻ 루틴</span>}</span><span className="day-plan-count">{count.filter(t=>t.complete).length} / {count.length} 완료</span></summary>
   {rows.map(t=><div className={'day-task'+(t.complete?' done':'')+(t.skipped?' routine-skipped':'')+(selectedId===t.id?' selected':'')} key={t.id}>
    <label className="task-check"><input type="checkbox" checked={t.complete} disabled={blocked||!!t.skipped} aria-label={t.title+' 완료 상태'} onChange={e=>void send('set_task_complete',{taskId:t.id,complete:e.target.checked})}/></label>
    <button type="button" className="day-task-title" draggable={!mobile&&!t.complete&&!t.skipped} onDragStart={e=>e.dataTransfer.setData('application/haru-task',t.id)} aria-pressed={selectedId===t.id} onClick={()=>choose(t.id)} title="선택하여 시간 배치와 실행 기록"><strong data-typo-role="title">{t.routine_id?'↻ ':''}{t.title}</strong><small>{t.skipped?'건너뛰기':`예상 ${duration(t.estimated_minutes*60000)} · ${data?.placements.some(v=>v.task_id===t.id)?'배치 '+data.placements.filter(v=>v.task_id===t.id).length+'건':'시간 미정'}`}{t.routine_exception?' · 개별 수정':''}</small></button>
    <details className="day-task-more"><summary aria-label={t.title+' 수정 메뉴'}>⋯</summary><div className="action-menu-panel"><button className="btn sm" disabled={locked} onClick={()=>{choose(t.id);if(t.routine_id)setRoutineEditing(t);else setTaskEditing(t);}}>할 일 수정</button></div></details>
   </div>)}</details>;})}</div><p className="day-rail-note">일반 할 일 전체 · 루틴은 선택 날짜 기준</p></>;}
 const title=view==='weekly'?dateText(days[0])+'–'+dateText(days[6]):view==='monthly'?Number(day.slice(0,4))+'년 '+Number(day.slice(5,7))+'월':dateText(day,true);
 const eyebrow=view==='weekly'?'한 주의 배치와 실제 기록':view==='monthly'?'월간 일정':day===today?'오늘의 일간 기록':future?'미리 세운 계획':'지난 날짜의 기록';
 return <><div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1 data-typo-role="title">{title}</h1></div><div className="viewtabs" aria-label="일정 보기">{([['daily','일간'],['weekly','주간'],['monthly','월간']] as const).map(([id,label])=><button key={id} data-typo-role="menu" aria-pressed={view===id} onClick={()=>{setView(id);setEditor(null);}}>{label}</button>)}</div></div>
 <div className="row spread period-head">{view==='daily'?<div className="date-tools"><button className="btn sm" aria-label="이전 날짜" onClick={()=>shift(-1)}>‹</button><DateField compact label="조회 날짜" value={day} required onChange={v=>{setDay(v);setSelectedId('');}} display={dateButtonText(day)}/><button className="btn sm" aria-label="다음 날짜" onClick={()=>shift(1)}>›</button>{day!==today&&<button className="btn sm" onClick={()=>openDay(today)}>오늘로</button>}</div>:<div className="period-tools" aria-label={view==='weekly'?'주 이동':'월 이동'}><button className="btn sm" onClick={()=>shift(-1)}>{view==='weekly'?'‹ 이전 주':'‹ 이전 달'}</button><button className="btn sm" data-action="period-today" onClick={()=>setDay(today)}>{view==='weekly'?'이번 주':'이번 달'}</button><button className="btn sm" onClick={()=>shift(1)}>{view==='weekly'?'다음 주 ›':'다음 달 ›'}</button></div>}</div>
 {!data&&<p className="empty">저장소에서 기록을 불러오고 있습니다.</p>}
 {view==='daily'&&<><div className="daystrip" aria-label="일요일부터 토요일까지 날짜 선택">{days.map((d,i)=><button className={'daycell'+(d===today?' today':'')} key={d} aria-pressed={day===d} aria-label={dateText(d,true)} onClick={()=>openDay(d)}><span data-typo-role="menu">{weekdays[i]}</span><b data-typo-role="number">{Number(d.slice(8))}</b><span className="today-caption" data-typo-role="info">{d===today?'오늘':' '}</span>{data?.placements.some(p=>seoulDate(new Date(p.started_at))===d)&&<i className="dot"/>}</button>)}</div>
 {data&&!data.plans.length?<section className="welcome"><div className="eyebrow">첫 계획부터 시작</div><h2 data-typo-role="title">계획한 일과 실제로 한 일을,<br/>한곳에 기록합니다.</h2><p>현재 진행하는 일 하나로 시작할 수 있습니다. 먼저 계획을 만들고, 할 일을 추가한 다음 시간을 정하거나 기록을 시작합니다.</p><button className="btn primary" onClick={onPlan}>첫 계획 만들기</button></section>:<div className={'day-layout'+(listCollapsed?' sidebar-collapsed':'')}>
  <aside className="day-rail" id="daily-task-list" aria-label="계획별 할 일"><div className="day-rail-head"><div><h2 data-typo-role="title">할 일 목록</h2><p>{eligible.filter(t=>t.complete).length} / {eligible.length} 완료</p></div><button className="day-rail-toggle" aria-label={listCollapsed?'할 일 목록 펼치기':'할 일 목록 접기'} aria-expanded={!listCollapsed} onClick={()=>setListCollapsed(v=>!v)}><ListIcon collapsed={listCollapsed}/></button></div><div className="day-rail-body">{listBody()}</div></aside>
  <details className="mobile-task-fold" open={mobileOpen} onToggle={e=>setMobileOpen(e.currentTarget.open)}><summary><span>할 일 목록</span><span>{eligible.filter(t=>t.complete).length} / {eligible.length} 완료</span></summary>{listBody(true)}</details>
  <div className="day-main">
   <section ref={detail} className={'work'+(live?.task_id===selected?.id?' is-running':'')+(!selected?' work-empty':'')} id="work-panel" tabIndex={-1} key={day+':'+selectedId}>
    {!selected?<><h2 className="work-title" data-typo-role="title">목록에서 할 일을 선택하세요</h2><p className="work-meta">{future?'선택한 일의 예정 시간을 배치합니다.':'시간을 배치하거나 실행 기록을 남길 수 있습니다.'}</p></>:<>
     <div className="work-plan-heading"><span data-typo-role="info">소속 계획</span><h3 data-typo-role="title"><mark>{data?.plans.find(p=>p.id===selected.plan_id)?.title||data?.runs.find(r=>r.task_id===selected.id)?.plan_title||'지난 계획'}</mark></h3></div><div className="work-top"><div className="grow"><h2 className="work-title" data-typo-role="title">{selected.routine_id?'↻ ':''}{selected.title}</h2><label className="detail-complete"><input type="checkbox" checked={selected.complete} disabled={blocked||retained||!!selected.skipped||!!selected.cancelled_at} onChange={e=>void send('set_task_complete',{taskId:selected.id,complete:e.target.checked})}/>할 일 완료</label><p className="work-meta">예상 {duration(selected.estimated_minutes*60000)}{selected.routine_id?' · '+dateText(day):''}</p></div></div>
     {retained||selected.skipped||selected.cancelled_at?<p className="routine-note">{retained?'휴지통으로 이동한 할 일입니다.':selected.skipped?'건너뛴 날짜입니다.':'반복이 중단된 날짜입니다.'} 기존 기록은 보존되어 있습니다.</p>:live?.task_id===selected.id?<div className="work-controls actions"><button className="btn" disabled={locked} onClick={()=>void send('switch_segment',{runId:live.id,kind:live.segments.at(-1)?.kind==='work'?'pause':'work',at:new Date().toISOString()})}>{live.segments.at(-1)?.kind==='work'?'잠시 멈춤':'다시 시작'}</button><button className="btn primary" onClick={()=>{setStopAt(new Date().toISOString());setStop(live);setReason(live.blocked_reason);}}>기록 종료</button><span className="timer mono" data-typo-role="number">{duration(runWork(live,undefined,undefined,now))}</span></div>:<div className="work-action-groups"><div className="work-live-actions"><button className="btn primary" disabled={locked||selected.complete||!!live||day!==today} onClick={()=>void send('start_run',{taskId:selected.id,at:new Date().toISOString()})}>기록 시작</button>{(day!==today||live||selected.complete)&&<p className="start-reason">{selected.complete?'완료한 할 일입니다.':live?'진행 중인 기록을 마친 뒤 시작할 수 있습니다.':'기록 시작은 오늘 날짜에서 사용할 수 있습니다.'}</p>}</div><div className="work-input-actions"><button className="btn" disabled={locked||selected.complete} onClick={()=>setEditor({task:selected,mode:'placement'})}>계획 배치</button>{!future&&<button className="btn" disabled={locked} onClick={()=>setEditor({task:selected,mode:'run'})}>실행 기록 입력</button>}</div></div>}
     {live?.task_id===selected.id&&<div className="active-record-start" tabIndex={-1} ref={actualStart}><span>기록 시작</span><strong>{dateText(seoulDate(new Date(live.started_at)))} · {clockLabel(live.started_at)}</strong><small>{live.segments.at(-1)?.kind==='work'?'기록 중':'잠시 멈춤'}</small></div>}
   {editor&&!editor.startAt&&<div ref={editorPanel}><RunEditor key={editor.placementId||editor.runId||editor.task.id+editor.mode} task={editor.task} day={day} mode={editor.mode} startAt={editor.startAt} run={data?.runs.find(r=>r.id===editor.runId)} placement={data?.placements.find(p=>p.id===editor.placementId)} onClose={()=>setEditor(null)}/></div>}
     <div className="work-history">
      {!!data?.placements.some(p=>p.task_id===selected.id&&overlaps(p.started_at,p.ended_at,day,now))&&<details ref={planned} open={placementOpen} onToggle={e=>setPlacementOpen(e.currentTarget.open)}><summary>예정 시간 <span>{data.placements.filter(p=>p.task_id===selected.id&&overlaps(p.started_at,p.ended_at,day,now)).length}건</span></summary><div className="work-history-body">{data.placements.filter(p=>p.task_id===selected.id&&overlaps(p.started_at,p.ended_at,day,now)).map(p=><div className={'record-row'+(selection?.kind==='placement'&&selection.id===p.id?' selected-placement':'')} key={p.id}><div className="row spread"><span>{dateText(seoulDate(new Date(p.started_at)))} · {clockLabel(p.started_at)}–{clockLabel(p.ended_at)}</span><div className="actions"><button className="btn sm" disabled={locked||retained||selected.complete} onClick={()=>setEditor({task:selected,mode:'placement',placementId:p.id})}>시간 변경</button><button className="btn sm" disabled={locked||retained||selected.complete} onClick={()=>{if(window.confirm('이 예정 배치를 휴지통으로 옮길까요?'))void send('delete_entity',{entityType:'placement',entityId:p.id,at:new Date().toISOString()});}}>삭제</button></div></div></div>)}</div></details>}
      {selected.description&&<details><summary>설명</summary><p className="record-body" data-typo-role="record">{selected.description}</p></details>}
      {(data?.thoughts.some(t=>t.task_id===selected.id&&t.local_date===day)||data?.runs.some(r=>r.task_id===selected.id&&r.segments.some(s=>s.kind==='work'&&overlaps(s.started_at,s.ended_at,day,now))))&&<ThoughtEditor task={selected} day={day} readOnly={retained||!data?.runs.some(r=>r.task_id===selected.id&&r.segments.some(s=>s.kind==='work'&&overlaps(s.started_at,s.ended_at,day,now)))}/>}
      {!!data?.runs.some(r=>r.ended_at&&r.task_id===selected.id&&overlaps(r.started_at,r.ended_at,day,now))&&<details open={historyOpen} onToggle={e=>setHistoryOpen(e.currentTarget.open)}><summary>실행 기록 <span>{data.runs.filter(r=>r.ended_at&&r.task_id===selected.id&&overlaps(r.started_at,r.ended_at,day,now)).length}건</span></summary><div className="work-history-body">{data.runs.filter(r=>r.ended_at&&r.task_id===selected.id&&overlaps(r.started_at,r.ended_at,day,now)).map(r=><div className="record-row" key={r.id}><div className="record-row-head"><div><span className="title">{dateText(seoulDate(new Date(r.started_at)))} · {clockLabel(r.started_at)}–{r.ended_at?clockLabel(r.ended_at):'기록 중'}</span><div className="record-row-meta"><span>작업 {duration(runWork(r,undefined,undefined,now))}</span>{r.source==='manual'&&<span className="record-source">수기 기록</span>}</div></div>{r.ended_at&&<button className="btn sm record-edit" disabled={locked||retained} onClick={()=>setEditor({task:selected,mode:'run',runId:r.id})}>수정</button>}</div>{r.blocked_reason&&<p className="blocked-reason-text" data-typo-role="record"><span data-typo-role="info">막힌 이유</span>{r.blocked_reason}</p>}{r.segments.some(s=>s.kind!=='work')&&<details className="record-advanced"><summary>휴식·중단 구간</summary><ul>{r.segments.filter(s=>s.kind!=='work').map(s=><li key={s.id}>{s.kind==='work'?'작업':s.kind==='break'?'휴식':'중단'} · {clockLabel(s.started_at)}–{s.ended_at?clockLabel(s.ended_at):'기록 중'}</li>)}</ul></details>}<button className="link record-delete" disabled={locked||retained} onClick={()=>{if(window.confirm('이 실행 기록을 휴지통으로 옮길까요? 단상과 회고는 유지됩니다.'))void send('delete_entity',{entityType:'run',entityId:r.id,at:new Date().toISOString()});}}>기록 삭제</button></div>)}</div></details>}
     </div>
     {selected.routine_id&&!retained&&<div className="actions"><button className="link" disabled={locked} onClick={()=>setRoutineEditing(selected)}>반복 할 일 수정</button><button className="link" disabled={locked||selected.complete||!!selected.skipped||!!selected.cancelled_at||live?.task_id===selected.id} onClick={()=>{if(window.confirm('이 날짜의 반복 할 일을 건너뛸까요? 단상과 실제 기록은 유지됩니다.'))void send('skip_occurrence',{taskId:selected.id});}}>이 날짜 건너뛰기</button></div>}
    </>}
    <button className="btn sm day-list-shortcut" onClick={()=>{setListCollapsed(false);setMobileOpen(true);document.querySelector('.mobile-task-fold')?.scrollIntoView({block:'start'});}}>할 일 목록</button>
   </section>
   {taskEditing&&<TaskEditor key={taskEditing.id} task={taskEditing} planId={taskEditing.plan_id} onSaved={()=>setTaskEditing(null)} onCancel={()=>setTaskEditing(null)}/>}
   {routineEditing&&data?.routines?.find(r=>r.id===routineEditing.routine_id)&&data.plans.find(p=>p.id===routineEditing.plan_id)&&<RoutineEditor key={routineEditing.id} plan={data.plans.find(p=>p.id===routineEditing.plan_id)!} rule={data.routines.find(r=>r.id===routineEditing.routine_id)} task={routineEditing} onClose={()=>setRoutineEditing(null)}/>}
   {data&&<Timeline data={data} day={day} now={now} early={early} selection={selection} choose={chooseTimeline} onEarly={()=>setEarly(v=>!v)} onDrop={(task,startAt)=>{choose(task.id);setEditor({task,mode:'placement',startAt});}}/>}
   <DayClosing key={day} day={day} onArchive={onArchive} onCurrent={id=>openDay(today,id)}/>
  </div>
 </div>}</>}
 {data&&view==='weekly'&&<Weekly data={data} days={days} today={today} expanded={expanded} setExpanded={setExpanded} openDay={openDay}/>}
 {data&&view==='monthly'&&<Monthly data={data} day={day} today={today} selectDay={setDay} openDay={openDay}/>}
 {editor?.startAt&&data&&<DropConfirmation task={editor.task} data={data} startAt={editor.startAt} onClose={()=>setEditor(null)}/>}
 {stop&&<div className="modal-backdrop"><section className="stop-dialog" role="dialog" aria-modal="true" aria-labelledby="stop-title"><div className="editor-head"><h2 id="stop-title" data-typo-role="title">기록 종료</h2><button className="iconbtn" aria-label="닫기" onClick={()=>setStop(null)}>×</button></div><label className="field"><span>막힌 이유 · 선택</span><textarea data-typo-role="record-input" maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="form-help">종료해도 할 일의 완료 상태는 바뀌지 않습니다.</p><div className="form-actions"><button className="btn primary" disabled={locked} onClick={async()=>{if(await send('stop_run',{runId:stop.id,at:stopAt,blockedReason:reason}))setStop(null);}}>기록 종료</button></div></section></div>}
 </>;
}
function Weekly({data,days,today,expanded,setExpanded,openDay}:{data:Snapshot;days:string[];today:string;expanded:string;setExpanded:(v:string)=>void;openDay:(d:string,id?:string)=>void}){
 const values=days.map(d=>{const v=dayItems(data,d),{from,to}=dayWindow(d),closed=v.runs.filter(r=>r.ended_at),due=data.tasks.filter(t=>!t.skipped&&!t.cancelled_at&&t.due_date===d);return {day:d,...v,closed,due,planned:v.placements.reduce((n,p)=>n+Math.max(0,Math.min(to,Date.parse(p.ended_at))-Math.max(from,Date.parse(p.started_at))),0),actual:closed.reduce((n,r)=>n+runWork(r,from,to),0)};});
 return <section id="weekly-overview" aria-label="주간 전체 요약"><div className="week-totals">{[['배치 시간',duration(values.reduce((n,v)=>n+v.planned,0))],['실제 작업',duration(values.reduce((n,v)=>n+v.actual,0))],['마감 할 일',values.reduce((n,v)=>n+v.due.length,0)+'개']].map(([name,value])=><div key={name}><span>{name}</span><strong data-typo-role="number">{value}</strong></div>)}</div><p className="week-explanation">예정은 시간표에 배치한 계획, 실제는 종료한 기록입니다. 실제 작업 시간에는 멈춘 시간이 포함되지 않습니다.</p><div className="weekly-grid">{values.map((v,i)=>{const limit=expanded===v.day?Infinity:3,{from,to}=dayWindow(v.day);function entry(value:{id:string;task_id:string;started_at:string;ended_at:string|null},actual=false){const t=allTasks(data).find(t=>t.id===value.task_id),range=clockLabel(Math.max(from,Date.parse(value.started_at)))+'–'+(Date.parse(value.ended_at!)>=to?'다음 날 00:00':clockLabel(value.ended_at!));return <li className="week-list-item" key={value.id}><button className="week-entry" onClick={()=>openDay(v.day,value.task_id)}><span className="week-entry-title" data-typo-role="title">{t?.title||('task_title' in value?String(value.task_title):'지난 할 일')}</span><span className="week-entry-time">{range}{actual?' · 작업 '+duration(runWork(value as Run,from,to)):''}</span><span className="week-entry-priority">우선순위 {priorityText(t?.priority||'normal')}{t?.complete?' · 완료':''}</span></button></li>;}
 return <article className={'week-day'+(v.day===today?' is-today':'')} key={v.day}><header><h2 data-typo-role="number"><span>{weekdays[i]}</span> {Number(v.day.slice(8))}</h2>{v.day===today&&<span className="week-today">오늘</span>}</header><dl className="week-day-totals"><div><dt>배치</dt><dd>{duration(v.planned)}</dd></div><div><dt>실제</dt><dd>{duration(v.actual)}</dd></div></dl>{!!v.placements.length&&<section className="week-section planned"><h3>예정</h3><ul className="week-items">{v.placements.slice(0,limit).map(p=>entry(p))}</ul></section>}{!!v.closed.length&&<section className="week-section actual"><h3>실제</h3><ul className="week-items">{v.closed.slice(0,limit).map(r=>entry(r,true))}</ul></section>}{!!v.due.length&&<section className="week-section due"><h3>마감 {v.due.length}개</h3><ul className="week-items">{v.due.slice(0,limit).map(t=><li className="week-list-item" key={t.id}><button className="week-entry" onClick={()=>openDay(v.day,t.id)}><span className="week-entry-title" data-typo-role="title">{t.title}</span><span className="week-entry-priority">{t.complete?'완료':v.day<today?'미완료 · 지연':'미완료'}</span></button></li>)}</ul></section>}{[v.placements,v.closed,v.due].some(rows=>rows.length>3)&&<button className="link week-expand" aria-expanded={expanded===v.day} onClick={()=>setExpanded(expanded===v.day?'':v.day)}>{expanded===v.day?'접기':'외 '+[v.placements,v.closed,v.due].reduce((n,rows)=>n+Math.max(0,rows.length-3),0)+'개 보기'}</button>}<button className="link week-day-link" onClick={()=>openDay(v.day)}>일간 상세 →</button></article>;
 })}</div></section>;
}
function DropConfirmation({task,data,startAt,onClose}:{task:Task;data:Snapshot;startAt:string;onClose:()=>void}){
 const {send,locked}=useJournal(),dialog=useRef<HTMLDialogElement>(null),[confirmed,setConfirmed]=useState(false);const minutes=Math.max(1,task.estimated_minutes),end=new Date(Date.parse(startAt)+minutes*60000).toISOString(),conflicts=data.placements.filter(p=>Date.parse(p.started_at)<Date.parse(end)&&Date.parse(p.ended_at)>Date.parse(startAt));
 useEffect(()=>{const el=dialog.current;el?.showModal();return()=>{if(el?.open)el.close();};},[]);
 return <dialog id="drop-dialog" ref={dialog} aria-labelledby="drop-title" onCancel={e=>{e.preventDefault();if(!locked)onClose();}}><div className="modal-title-line"><div><div className="eyebrow">SCHEDULE</div><h2 id="drop-title" data-typo-role="title">계획 배치 확인</h2></div><button className="iconbtn" disabled={locked} aria-label="배치 확인 닫기" onClick={onClose}>×</button></div><p className="drop-task-title" data-typo-role="title">{task.title}</p><p className="drop-date">{dateText(seoulDate(new Date(startAt)),true)} · {data.plans.find(p=>p.id===task.plan_id)?.title}</p><dl className="drop-facts"><div><dt>시작 시각</dt><dd>{clockLabel(startAt)}</dd></div><div><dt>배치 시간</dt><dd>{duration(minutes*60000)}</dd></div><div><dt>예정 종료</dt><dd>{seoulDate(new Date(end))!==seoulDate(new Date(startAt))?dateText(seoulDate(new Date(end)))+' ':''}{clockLabel(end)}</dd></div></dl>{!!conflicts.length&&<div className="drop-warning"><p><strong>기존 일정 {conflicts.length}건과 시간이 겹칩니다.</strong></p><ul>{conflicts.map(p=><li key={p.id}>{allTasks(data).find(t=>t.id===p.task_id)?.title||'할 일'} · {clockLabel(p.started_at)}–{clockLabel(p.ended_at)}</li>)}</ul><label><input type="checkbox" disabled={locked} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 겹치는 시간을 확인했으며 그대로 배치</label></div>}<p className="dialog-helper">배치를 눌러야 예정 시간에 반영됩니다.</p><div className="actions"><button className="btn" disabled={locked} onClick={onClose}>취소</button><button className="btn primary" disabled={locked||task.complete||(!!conflicts.length&&!confirmed)} onClick={async()=>{if(await send('create_placement',{taskId:task.id,startedAt:startAt,endedAt:end,allowOverlap:confirmed}))onClose();}}>{locked?'반영 중…':'배치'}</button></div></dialog>;
}
