'use client';
import {useRef,useState} from 'react';
import {PickerDialog} from './picker-dialog';
export function TimeField({label,value,onChange,min='00:00',max='23:59'}:{label:string;value:string;onChange:(value:string)=>void;min?:string;max?:string}){
 const [open,setOpen]=useState(false),[choice,setChoice]=useState(value),[error,setError]=useState('');const button=useRef<HTMLButtonElement>(null);
 const hours=Number(choice.split(':')[0]||0),minutes=Number(choice.split(':')[1]||0),period=hours>=12?'pm':'am';
 const bound=(time:string)=>Number(time.slice(0,2))*60+Number(time.slice(3));const valid=(h:number,m:number)=>h*60+m>=bound(min)&&h*60+m<=bound(max),set=(h:number,m:number)=>{setChoice(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`);setError('');};
 return <div className="time-field field"><label className="field"><span>{label}</span><div className="clock-inputs"><input aria-label={label+" · 시"} data-typo-role="control" required inputMode="numeric" pattern="(?:[01]?[0-9]|2[0-3])" placeholder="09" maxLength={2} value={value.split(':')[0]||''} onBlur={e=>{if(/^\d{1,2}$/.test(e.target.value))onChange(e.target.value.padStart(2,'0')+':'+(value.split(':')[1]||'00'));}} onChange={e=>onChange(e.target.value+':'+(value.split(':')[1]||'00'))}/><span aria-hidden="true">:</span><input aria-label={label+" · 분"} data-typo-role="control" required inputMode="numeric" pattern="[0-5]?[0-9]" placeholder="00" maxLength={2} value={value.split(':')[1]||''} onBlur={e=>{if(/^\d{1,2}$/.test(e.target.value))onChange((value.split(':')[0]||'00')+':'+e.target.value.padStart(2,'0'));}} onChange={e=>onChange((value.split(':')[0]||'00')+':'+e.target.value)}/><button ref={button} className="clock-open" type="button" aria-label={label+' 시계 열기'} aria-haspopup="dialog" aria-expanded={open} onClick={()=>{setChoice(/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test(value)?value:'09:00');setError('');setOpen(true);}}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/></svg></button></div></label>{open&&<PickerDialog kind="time" anchor={button} onClose={()=>setOpen(false)}><div className="date-dialog-head"><h2>{label}</h2><button type="button" className="iconbtn" aria-label="시각 선택 닫기" onClick={()=>setOpen(false)}>×</button></div><div className="time-choice-line"><select aria-label="오전·오후" value={period} onChange={e=>set(hours%12+(e.target.value==='pm'?12:0),minutes)}><option value="am">오전</option><option value="pm">오후</option></select><output className="picker-time-preview">{choice}</output></div><p className="picker-step">1. 시 선택</p><div className="time-picker-grid">{Array.from({length:12},(_,i)=>{const h=i+(period==='pm'?12:0);return <button key={h} type="button" disabled={h*60+59<bound(min)||h*60>bound(max)} aria-pressed={h===hours} onClick={()=>set(h,minutes)}>{i===0?12:i}<small>{String(h).padStart(2,'0')}시</small></button>;})}</div><p className="picker-step">2. 분 선택</p><div className="time-picker-grid minutes">{Array.from({length:12},(_,i)=><button type="button" key={i} aria-pressed={i*5===minutes} disabled={!valid(hours,i*5)} onClick={()=>set(hours,i*5)}>{String(i*5).padStart(2,'0')}</button>)}</div><div className="picker-foot"><span className="tiny muted">정확한 분은 입력창에서 직접 입력할 수 있습니다.<br/>{min}–{max}</span><button className="btn primary sm" type="button" onClick={()=>{if(!valid(hours,minutes)){setError('실행 시작·종료 범위 안의 시각을 선택해 주세요.');return;}onChange(choice);setOpen(false);}}>적용</button></div>{error&&<p className="error" role="alert">{error}</p>}</PickerDialog>}</div>;
}
