'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {Snapshot,Task} from '@/lib/contracts';
import {clockLabel,dayWindow,seoulDate} from '@/lib/schedule';
import {priorityText} from './presentation';
export type TimelineSelection={id:string;kind:'placement'|'run';taskId:string};
type Tip={id:string;text:string;rect:{left:number;right:number;top:number;bottom:number}};
export function Timeline({data,day,now,early,selection,choose,onEarly,onDrop}:{data:Snapshot;day:string;now:number;early:boolean;selection:TimelineSelection|null;choose:(selection:TimelineSelection)=>void;onEarly:()=>void;onDrop:(task:Task,start:string)=>void}){
 const hour=76,startHour=early?0:6,{from}=dayWindow(day),begin=from+startHour*3600000,end=from+27*3600000,height=(27-startHour)*hour,allTasks=[...data.tasks,...(data.retainedTasks||[])];
 const [tip,setTip]=useState<Tip|null>(null),tipRef=useRef<HTMLDivElement>(null);
 useLayoutEffect(()=>{if(!tip||!tipRef.current)return;const el=tipRef.current,w=el.offsetWidth,h=el.offsetHeight,viewport=document.documentElement;el.style.left=Math.max(8,Math.min(viewport.clientWidth-w-8,tip.rect.left))+'px';el.style.top=Math.max(8,Math.min(viewport.clientHeight-h-8,tip.rect.bottom+h+16<viewport.clientHeight?tip.rect.bottom+8:tip.rect.top-h-8))+'px';},[tip]);
 useEffect(()=>{const hide=()=>setTip(null);const scroll=()=>setTip(current=>{const focused=document.activeElement;if(!current||!(focused instanceof HTMLButtonElement)||!focused.classList.contains('timeblock'))return null;const r=focused.getBoundingClientRect();return {...current,rect:{left:r.left,right:r.right,top:r.top,bottom:r.bottom}};});window.addEventListener('scroll',scroll,true);window.addEventListener('resize',hide);window.addEventListener('blur',hide);return()=>{window.removeEventListener('scroll',scroll,true);window.removeEventListener('resize',hide);window.removeEventListener('blur',hide);};},[]);
 useEffect(()=>{setTip(null);},[day,early]);
 const placements=data.placements.filter(p=>Date.parse(p.started_at)<end&&Date.parse(p.ended_at)>begin),runs=data.runs.filter(r=>Date.parse(r.started_at)<end&&(r.ended_at?Date.parse(r.ended_at):now)>begin);
 const sorted=[...placements].sort((a,b)=>Date.parse(a.started_at)-Date.parse(b.started_at)),groups:typeof placements[]=[];let group:typeof placements=[],groupEnd=0;
 for(const p of sorted){if(group.length&&Date.parse(p.started_at)>=groupEnd){groups.push(group);group=[];groupEnd=0;}group.push(p);groupEnd=Math.max(groupEnd,Date.parse(p.ended_at));}if(group.length)groups.push(group);
 function block(value:{id:string;task_id:string;started_at:string;ended_at:string|null},actual:boolean,column=0,columns=1){
  const a=Date.parse(value.started_at),z=value.ended_at?Date.parse(value.ended_at):now,h=Math.max(.75,(Math.min(z,end)-Math.max(a,begin))/3600000*hour),t=allTasks.find(t=>t.id===value.task_id),title=t?.title||('task_title' in value?String(value.task_title):'지난 할 일'),plan=data.plans.find(p=>p.id===t?.plan_id)?.title||('plan_title' in value?String(value.plan_title):'지난 계획'),priority=priorityText(t?.priority||'normal'),range=clockLabel(value.started_at)+'–'+(value.ended_at?clockLabel(value.ended_at):'기록 중'),density=h<18?'micro':h<50?'compact':'full',kind=actual?'run' as const:'placement' as const,selected=selection?.id===value.id&&selection.kind===kind,text=plan+'\n'+title+'\n'+(actual?'실제':'예정')+' · '+range+'\n우선순위 '+priority;
  function show(el:HTMLButtonElement){const r=el.getBoundingClientRect();setTip({id:value.id,text,rect:{left:r.left,right:r.right,top:r.top,bottom:r.bottom}});}
  return <button key={value.id} className={'timeblock '+(actual?'actual ':'')+'density-'+density+(selected?' selected':'')+(!value.ended_at?' live':'')} style={{top:(Math.max(a,begin)-begin)/3600000*hour,height:h,...(columns>1?{left:`calc(${column/columns*100}% + 4px)`,width:`calc(${100/columns}% - 8px)`,right:'auto'}:{})}} aria-label={plan+' · '+title+' · '+(actual?'실제':'계획')+' '+range} aria-pressed={selected} aria-describedby={tip?.id===value.id?'timeline-tooltip':undefined} onPointerEnter={e=>{if(e.pointerType!=='touch')show(e.currentTarget);}} onPointerLeave={e=>{if(document.activeElement!==e.currentTarget)setTip(null);}} onFocus={e=>show(e.currentTarget)} onBlur={()=>setTip(null)} onKeyDown={e=>{if(e.key==='Escape')setTip(null);}} onClick={()=>{setTip(null);choose({id:value.id,kind,taskId:value.task_id});}}>{density!=='micro'?<><span className="block-heading"><b data-typo-role="title">{title}</b><span className="block-priority">{priority}</span></span>{density==='full'&&<small>{range}</small>}</>:<span className="sr-only">{title} · {range}</span>}</button>;
 }
 return <section aria-label="계획과 실제 시간 비교"><div className="section-heading"><div className="timeline-heading"><button className="link early-hours" aria-expanded={early} onClick={onEarly}>{early?'00–06시 접기':'00–06시 펼치기'}</button><h2 data-typo-role="title">계획과 실제, 나란히</h2></div><div className="legend"><span><i/>계획</span><span><i className="actual"/>실제</span></div></div><div className="timeline-scroll" tabIndex={0} aria-label="세로 시간표. 위아래로 스크롤할 수 있습니다."><div className="timeline-labels"><div>시간</div><div>계획한 시간</div><div>실제로 한 일</div></div><div className="timeline" style={{height}}><div className="time-axis">{Array.from({length:28-startHour},(_,i)=><span className="hour-label" key={i} style={{top:i*hour}}>{i+startHour>=24?'다음 날 ':''}{String((i+startHour)%24).padStart(2,'0')}:00</span>)}</div><div className="lane planned-drop-lane" onDragOver={e=>{if(e.dataTransfer.types.includes('application/haru-task'))e.preventDefault();}} onDrop={e=>{const t=data.tasks.find(t=>t.id===e.dataTransfer.getData('application/haru-task'));if(!t||t.complete||t.skipped||t.cancelled_at)return;e.preventDefault();const minutes=Math.max(0,Math.min((27-startHour)*60-15,Math.round((e.clientY-e.currentTarget.getBoundingClientRect().top)/hour*60/15)*15));onDrop(t,new Date(begin+minutes*60000).toISOString());}}>{groups.flatMap(gr=>{const ends:number[]=[],cols:number[]=[];for(const p of gr){let c=ends.findIndex(end=>end<=Date.parse(p.started_at));if(c<0)c=ends.length;ends[c]=Date.parse(p.ended_at);cols.push(c);}return gr.map((p,i)=>block(p,false,cols[i],ends.length));})}{!placements.length&&<span className="lane-note">정해 둔 시간이 없습니다.</span>}</div><div className="lane">{runs.map(r=>block(r,true))}{now>=begin&&now<end&&<i className="now-line" style={{top:(now-begin)/3600000*hour}} aria-hidden="true"/>}{!runs.length&&<span className="lane-note">{day>seoulDate(now)?<>미래 날짜에는<br/>실제 기록을 시작할 수 없습니다.</>:'아직 기록이 없습니다.'}</span>}</div></div></div><div className="timeline-meta"><span>같은 높이는 같은 시간 · 높음/보통/낮음은 할 일 우선순위<br/>배치를 선택하면 전체 제목과 기록 상세를 확인할 수 있습니다.</span></div>{tip&&createPortal(<div id="timeline-tooltip" role="tooltip" className="timeline-tooltip" ref={tipRef}>{tip.text}</div>,document.body)}</section>;
}
