'use client';
import type {Snapshot} from '@/lib/contracts';
import {planCompletion,plansOnDay,tasksInPlan} from '@/lib/calendar-plans';
import {dayItems,dayWindow,runWork} from '@/lib/schedule';
import {duration} from '@/lib/review';

const weekdays=['일','월','화','수','목','금','토'];
export function Weekly({data,days,today,expanded,setExpanded,openDay}:{data:Snapshot;days:string[];today:string;expanded:string;setExpanded:(v:string)=>void;openDay:(d:string,id?:string)=>void}){
 const values=days.map(d=>{const v=dayItems(data,d),{from,to}=dayWindow(d),closed=v.runs.filter(r=>r.ended_at),due=data.tasks.filter(t=>!t.skipped&&!t.cancelled_at&&t.due_date===d),plans=plansOnDay(data,d);return {day:d,plans,due,planned:v.placements.reduce((n,p)=>n+Math.max(0,Math.min(to,Date.parse(p.ended_at))-Math.max(from,Date.parse(p.started_at))),0),actual:closed.reduce((n,r)=>n+runWork(r,from,to),0)};});
 return <section id="weekly-overview" aria-label="주간 전체 요약"><div className="week-totals">{[['배치 시간',duration(values.reduce((n,v)=>n+v.planned,0))],['실제 작업',duration(values.reduce((n,v)=>n+v.actual,0))],['마감 할 일',values.reduce((n,v)=>n+v.due.length,0)+'개']].map(([name,value])=><div key={name}><span>{name}</span><strong data-typo-role="number">{value}</strong></div>)}</div><p className="week-explanation">계획의 예정 기간과 현재 완료 수를 먼저 보여줍니다. 배치 시각과 실제 실행 기록은 일간에서 확인할 수 있습니다. 주간 합계의 실제 작업에는 멈춘 시간이 포함되지 않습니다.</p><div className="weekly-grid">{values.map((v,i)=>{const visible=expanded===v.day?v.plans:v.plans.slice(0,3);return <article className={'week-day'+(v.day===today?' is-today':'')} key={v.day}><header><h2 data-typo-role="number"><span>{weekdays[i]}</span> {Number(v.day.slice(8))}</h2>{v.day===today&&<span className="week-today">오늘</span>}</header><dl className="week-day-totals"><div><dt>배치</dt><dd>{duration(v.planned)}</dd></div><div><dt>실제</dt><dd>{duration(v.actual)}</dd></div></dl>{!!v.plans.length?<section className="week-section week-plans"><h3>계획</h3><ul className="week-items">{visible.map(plan=>{const count=planCompletion(data,plan,v.day),firstTask=tasksInPlan(data,plan,v.day)[0];return <li className="week-list-item" key={plan.id}><button className="week-entry" onClick={()=>openDay(v.day,firstTask?.id)}><span className="week-entry-title" data-typo-role="title">{plan.title}</span><span className="week-entry-priority">{plan.kind==='routine'&&count.total===0?'루틴 · 이날 할 일 없음':(plan.kind==='routine'?'루틴 · ':'')+count.done+'/'+count.total+' 완료'}</span></button></li>;})}</ul></section>:<p className="week-none">진행 기간에 걸친 계획이 없습니다.</p>}{v.plans.length>3&&<button className="link week-expand" aria-expanded={expanded===v.day} onClick={()=>setExpanded(expanded===v.day?'':v.day)}>{expanded===v.day?'계획 접기':'계획 '+(v.plans.length-3)+'개 더 보기'}</button>}<button className="link week-day-link" onClick={()=>openDay(v.day)}>일간 상세 →</button></article>;})}</div></section>;
}
